// Generated by tools/workflows.py; edit contract/workflows.json.
export type SkillScope = "case_work";
export type SkillAvailability = "usable" | "dependencies_unavailable" | "retired";
export type SkillMutationPosture = "recorded" | "not_recorded";
export interface SkillDefinition {
  name: string;
  description: string;
  instructions: string;
  required_capabilities: Array<string>;
  required_resources: Array<string>;
  prerequisites: Array<string>;
  scope: SkillScope;
  provenance_refs: Array<string>;
}
export interface SkillDraft {
  schema: string;
  tenant_ref: string;
  skill_ref: string;
  revision: number;
  definition: SkillDefinition;
  created_by_principal_ref: string;
  created_at_unix_ms: number;
  content_digest: string;
}
export interface SkillVersion {
  schema: string;
  tenant_ref: string;
  skill_ref: string;
  version: number;
  version_ref: string;
  draft_revision: number;
  definition: SkillDefinition;
  published_by_principal_ref: string;
  published_at_unix_ms: number;
  content_digest: string;
}
export interface SkillRetirement {
  version_ref: string;
  retired_by_principal_ref: string;
  retired_at_unix_ms: number;
  reason: string;
}
export interface SkillAssignment {
  schema: string;
  assignment_ref: string;
  tenant_ref: string;
  case_ref: string;
  participant_ref?: string | null;
  skill_ref: string;
  version: number;
  version_ref: string;
  version_digest: string;
  assigned_by_principal_ref: string;
  assigned_at_generation: number;
  assigned_at_unix_ms: number;
  integrity_digest: string;
}
export interface SkillAssignmentDisabled {
  assignment_ref: string;
  disabled_by_principal_ref: string;
  disabled_at_generation: number;
  reason: string;
}
export interface SkillLibraryEntry {
  tenant_ref: string;
  skill_ref: string;
  draft?: SkillDraft | null;
  versions: Array<SkillVersion>;
  retirements: Array<SkillRetirement>;
}
export type SkillLibrary = Array<SkillLibraryEntry>;
export interface CaseSkillEntry {
  assignment: SkillAssignment;
  version: SkillVersion;
  availability: SkillAvailability;
  reasons: Array<string>;
}
export interface CaseSkillView {
  schema: string;
  case_ref: string;
  participant_ref: string;
  case_generation: number;
  capability_view_ref: string;
  effective_policy_ref: string;
  entries: Array<CaseSkillEntry>;
}
export interface SkillValidation {
  schema: string;
  skill_ref: string;
  draft_revision: number;
  content_digest: string;
  valid: boolean;
  reasons: Array<string>;
}
export type SkillMutationResult = { kind: "draft_saved"; value: SkillDraft } | { kind: "version_published"; value: SkillVersion } | { kind: "version_retired"; value: SkillRetirement } | { kind: "case_assigned"; value: SkillAssignment } | { kind: "case_disabled"; value: SkillAssignmentDisabled };
export interface SkillMutationReceipt {
  schema: string;
  tenant_ref: string;
  request_ref: string;
  principal_ref: string;
  operation_ref: string;
  result: SkillMutationResult;
}
export interface SkillMutationObservation {
  schema: string;
  tenant_ref: string;
  request_ref: string;
  posture: SkillMutationPosture;
  receipt?: SkillMutationReceipt | null;
}
export interface SkillListInput {
  tenant_ref: string;
}
export interface SkillGetInput {
  tenant_ref: string;
  skill_ref: string;
}
export interface SkillDraftSaveInput {
  tenant_ref: string;
  skill_ref: string;
  definition: SkillDefinition;
  expected_revision: number;
}
export interface SkillValidateInput {
  tenant_ref: string;
  skill_ref: string;
  expected_revision: number;
}
export interface SkillPublishInput {
  tenant_ref: string;
  skill_ref: string;
  expected_revision: number;
  expected_latest_version: number;
}
export interface SkillRetireInput {
  tenant_ref: string;
  skill_ref: string;
  version: number;
  expected_digest: string;
  reason: string;
}
export interface CaseSkillAssignInput {
  case_ref: string;
  participant_ref?: string | null;
  skill_ref: string;
  version: number;
  expected_digest: string;
  expected_generation: number;
}
export interface CaseSkillDisableInput {
  case_ref: string;
  assignment_ref: string;
  expected_generation: number;
  reason: string;
}
export interface CaseSkillListInput {
  case_ref: string;
  participant_ref: string;
}
export interface SkillMutationGetInput {
  tenant_ref: string;
  mutation_request_ref: string;
}
export interface EmptyInput {
}
export interface FastSearchInput {
  working_state: unknown;
  max_candidates: number;
}
export interface FastSearchCandidate {
  candidate_id: string;
  candidate_kind: string;
  description: string;
  semantic_refs: Array<string>;
}
export interface FastSearchDecisionBudget {
  max_candidates: number;
  max_result_bytes: number;
  max_compute_millis: number;
}
export interface FastSearchDecisionRequest {
  schema: string;
  request_id: string;
  case_id: string;
  case_generation: number;
  participant_id: string;
  task_id: string;
  working_state_id: string;
  decision_kind: string;
  candidates: Array<FastSearchCandidate>;
  budget: FastSearchDecisionBudget;
}
export interface FastSearchChoice {
  candidate: FastSearchCandidate;
  origin: unknown;
}
export type FastSearchPreparationPosture = "ready_for_optional_producer" | "deterministic_fallback_no_choice";
export interface FastSearchNavigation {
  schema: string;
  navigation_id: string;
  working_state_id: string;
  posture: FastSearchPreparationPosture;
  choices: Array<FastSearchChoice>;
  omitted_optional_choices: number;
  decision_request?: FastSearchDecisionRequest | null;
}
export interface FastSearchScore {
  candidate_id: string;
  value: number;
}
export type FastSearchPosture = "scored" | "deterministic_fallback";
export type FiniteDispatchPosture = "not_attempted" | "not_dispatched" | "completed" | "outcome_unavailable";
export interface FiniteComputationObservation {
  dispatch: FiniteDispatchPosture;
  request_ref?: string | null;
  result_ref?: string | null;
  engine_generation?: number | null;
  producer_compute_nanoseconds?: number | null;
  caller_nanoseconds?: number | null;
  token_count?: number | null;
  model_forward_count?: number | null;
}
export interface FiniteProviderTransport {
  user: string;
  pinned_known_hosts: string;
  enrolled_client_key: string;
  device_identity: string;
  authenticated_peer: string;
  source_identity: string;
  logical_model_identity: string;
  binding_identity: string;
  tokenizer_identity: string;
  physical_program_identity: string;
  input_policy_identity: string;
}
export interface FiniteProviderRegisterInput {
  tenant_id: string;
  provider_key: string;
  adapter: string;
  endpoint: string;
  model_id: string;
  credential_ref: string;
  locality: string;
  finite_transport: FiniteProviderTransport;
}
export interface FiniteProviderTarget {
  schema: string;
  target_id: string;
  integrity_digest: string;
  tenant_id: string;
  provider_key: string;
  adapter: string;
  endpoint: string;
  model_id: string;
  credential_ref: string;
  locality: string;
  extension_adapter_id?: string | null;
  finite_transport: FiniteProviderTransport;
  created_by_principal_id: string;
  created_at_unix_ms: number;
}
export interface FiniteQualifyInput {
  target_ref: string;
  working_state: unknown;
  max_candidates: number;
  expected_generation: number;
  valid_for_ms: number;
}
export interface FiniteQualifyResult {
  schema: string;
  compatible: boolean;
  qualification_ref?: string | null;
  navigation_ref: string;
  decision_request_ref: string;
  computations: Array<FiniteComputationObservation>;
  reason: string;
}
export interface FastSearchRanking {
  schema: string;
  ranking_id: string;
  navigation_id: string;
  distribution_id: string;
  ordered_candidate_ids: Array<string>;
  preferred_candidate_id?: string | null;
}
export interface FiniteProducerIdentity {
  capability_id: string;
  producer_id: string;
  producer_version: string;
  model_id?: string | null;
  composition_id?: string | null;
  profile_id?: string | null;
  state_generation?: string | null;
  evidence_refs: Array<string>;
}
export type CognitiveStepTier = "deterministic" | "system_one" | "general_llm" | "unavailable";
export type FiniteProducerPosture = "no_public_qualified_producer" | "qualified";
export interface FastSearchRoute {
  schema: string;
  request_ref?: string | null;
  participant_ref: string;
  selected_tier: CognitiveStepTier;
  producer_posture: FiniteProducerPosture;
  reason: string;
  general_llm_equivalent_qualified: boolean;
}
export interface FastSearchResult {
  schema: string;
  posture: FastSearchPosture;
  navigation: FastSearchNavigation;
  route: FastSearchRoute;
  binding_ref?: string | null;
  qualification_ref?: string | null;
  target_ref?: string | null;
  ranking?: FastSearchRanking | null;
  producer?: FiniteProducerIdentity | null;
  score_semantics?: string | null;
  score_scale?: number | null;
  scores: Array<FastSearchScore>;
  computation: FiniteComputationObservation;
  reason: string;
}
export type ProductAccessSource = "commercial" | "local_development" | "unconfigured_pre_release";
export type ProductAccessSourcePosture = "allowed" | "refused" | "not_enforced";
export type AccountProfilePosture = "not_applicable" | "authentication_required" | "unavailable" | "current" | "stale" | "unsupported_contract";
export type EmailVerificationPosture = "not_reported" | "verified" | "unverified";
export interface ProductDevelopmentAccessInput {
  expected_revision: number;
}
export interface ProductAccountProfileObservation {
  schema: string;
  posture: AccountProfilePosture;
  account_ref?: string | null;
  display_name?: string | null;
  email?: string | null;
  email_verification: EmailVerificationPosture;
  observed_at_unix_ms?: number | null;
  reason?: string | null;
}
export interface ProductAccessSourceObservation {
  schema: string;
  source: ProductAccessSource;
  posture: ProductAccessSourcePosture;
  operation_allowed: boolean;
  development_capable: boolean;
  development_enabled: boolean;
  profile_revision?: number | null;
  commercial_limits_applied: boolean;
  commercial_auth?: ProductAuthObservation | null;
  account_profile: ProductAccountProfileObservation;
  refusal?: string | null;
}
export interface CaseRefInput {
  case_ref: string;
}
export interface CaseCreateInput {
  tenant_id: string;
  case_ref: string;
}
export interface IdentityBootstrapInput {
  tenant_id: string;
  organization_ref: string;
}
export interface TenantInput {
  tenant_id: string;
}
export interface ParticipantRoleInput {
  case_ref: string;
  participant_ref: string;
  role: string;
}
export interface ReviewResolveInput {
  case_ref: string;
  review_ref: string;
  participant_ref?: string;
  reason: string;
}
export interface MaterialReadInput {
  case_ref: string;
  source_ref: string;
  revision_ref?: string;
  path: string;
  expected_generation?: number;
}
export interface MaterialReadResult {
  case_ref: string;
  generation: number;
  source_ref: string;
  revision_ref: string;
  path: string;
  digest: string;
  bytes: number;
  media_type: string;
  encoding: string;
  content: string;
}
export interface ReviewActionProjection {
  schema: string;
  action_id: string;
  integrity_digest: string;
  review_id: string;
  operation_id: string;
  case_id: string;
  reviewer_participant_id: string;
  principal_id?: string;
  tenant_id?: string;
  action: string;
  reason: string;
  expected_case_generation: number;
  source: string;
}
export interface ReviewResolveResult {
  review_ref: string;
  action: ReviewActionProjection;
  effective_decision_ref?: string;
  state: CaseVersionProjection;
  external_effect: boolean;
}
export interface PrincipalProjection {
  principal_id: string;
  authentication_method: string;
}
export interface TenantProjection {
  tenant_id: string;
  organization_ref: string;
}
export interface TenantMembershipProjection {
  membership: string;
  tenant: TenantProjection;
}
export interface AuthenticationProjection {
  binding_ref: string;
}
export interface IdentityPresentation {
  principal: PrincipalProjection;
  tenants: Array<TenantMembershipProjection>;
  authentication: AuthenticationProjection;
}
export interface KnowledgeRequest {
  case_id: string;
  source?: string | null;
  revision?: string | null;
  max_units: number;
}
export interface KnowledgeInspectInput {
  request: KnowledgeRequest;
}
export interface KnowledgeSearchInput {
  request: KnowledgeRequest;
  query: string;
  limit: number;
}
export interface KnowledgeResolveInput {
  request: KnowledgeRequest;
  unit_ref: string;
}
export interface KnowledgeUnit {
  id: string;
  source: string;
  text: string;
  kind: string;
  posture: string;
  parent?: string | null;
  location?: unknown;
  entity?: string | null;
  predicate?: string | null;
  value?: unknown | null;
  references?: Array<string>;
  topics?: Array<string>;
}
export interface KnowledgeSource {
  id: string;
  path: string;
  source_id?: string;
  logical_name?: string;
  revision_id?: string;
  current_revision?: boolean;
  digest?: string;
  bytes?: number;
  backing?: KnowledgeSourceBacking;
  roles?: Array<KnowledgeSourceRole>;
  resource_id?: string;
  media_type?: string;
  source_kind?: string;
  extractor?: string;
  extraction_id?: string;
  status?: string;
  detail?: string;
}
export interface KnowledgeRelation {
  id: string;
  from: string;
  to: string;
  kind: string;
  posture?: string;
  backing_units?: Array<string>;
}
export interface KnowledgeView {
  id: string;
  case_id: string;
  units: Array<KnowledgeUnit>;
  sources: Array<KnowledgeSource>;
  relations: Array<KnowledgeRelation>;
  schema?: string;
  requesting_principal?: string;
  profile?: string;
  entities?: Array<KnowledgeEntity>;
  topics?: Array<KnowledgeTopic>;
  contradictions?: Array<RecallKnowledgeConflict>;
  source_closure?: string;
  max_units?: number;
}
export interface KnowledgeHit {
  document_id: string;
  score_micros: number;
  matched_terms: Array<string>;
}
export interface KnowledgeSearchResult {
  view: KnowledgeView;
  hits: Array<KnowledgeHit>;
}
export interface KnowledgeResolveResult {
  view: KnowledgeView;
  unit: KnowledgeUnit;
}
export interface KnowledgeNavigationResult {
  view_ref: string;
  navigation: string;
}
export interface CaseVersionProjection {
  case_id: string;
  generation: number;
}
export interface WorkCommit {
  state: CaseVersionProjection;
  transition: TransitionReceipt;
}
export interface TransitionReceipt {
  transition_id: string;
  payload: TransitionReceiptPayload;
}
export interface TransitionReceiptPayload {
  kind: string;
  data: TransitionReceiptData;
}
export interface TransitionReceiptData {
  patch?: WorkflowPatchReceipt;
  offer?: HandoffOfferReceipt;
  acceptance?: HandoffReceipt;
  decline?: HandoffReceipt;
  result?: HandoffReceipt;
  reconciliation?: HandoffReceipt;
}
export interface WorkflowPatchReceipt {
  patch_id: string;
  base_effective_topology_digest: string;
}
export interface HandoffOfferReceipt {
  handoff_id: string;
  source_case_id: string;
  target_case_id: string;
}
export interface HandoffReceipt {
  handoff_id: string;
}
export interface CaseSummary {
  case_ref: string;
  display_name: string;
  case_status: string;
  generation: number;
  updated_at_unix_ms?: number | null;
  participant_count: number;
  source_count: number;
  resource_count: number;
  pending_review_count: number;
}
export interface CaseListProjection {
  cases: Array<CaseSummary>;
  authority: string;
}
export interface CaseAttachment {
  case_ref: string;
  case_status: string;
  generation: number;
  authenticated_principal: string;
  participant_ref: string;
  thread_ref?: string | null;
  attachment: "ephemeral";
}
export interface ApplicationCatalog {
  schema: "yai.application_capability_catalog.v1";
  application_protocol: string;
  operations: Array<ApplicationOperation>;
  capabilities: Array<ApplicationCapability>;
}
export interface ApplicationOperation {
  operation_id: string;
  meaning: string;
  input_contract: string;
  output_contract: string;
  impact: string;
  authority: string;
}
export interface ApplicationCapability {
  capability_id: string;
  meaning: string;
  application_posture: "ready" | "deferred" | "not_applicable";
  application_operation_ids: Array<string>;
  application_deferred_reason?: string | null;
  studio_posture: string;
}
export interface ParticipantLinkInput {
  case_ref: string;
  participant_ref: string;
  principal_ref: string;
}
export interface StateMutationReceipt {
  changed: boolean;
  transition_ref?: string;
  state: CaseVersionProjection;
}
export interface RegisteredModelsInput {
  tenant_id: string;
  target_ref: string;
}
export interface ModelInventory {
  target_ref?: string;
  observed_at_unix_ms?: number;
  models: Array<string>;
  scope: string;
  authority: string;
}
export interface ConversationTextPart {
  modality: TextModality;
  media_type: string;
  bytes: Array<number>;
}
export type TextModality = "text";
export type ContextDepth = "focused";
export interface ConversationIntent {
  context_depth?: ContextDepth;
  executor_participant_id?: string;
  work_limits?: CaseWorkLimits;
  workflow_execution_id?: string;
}
export interface CaseWorkLimits {
  invocations: number;
  operations: number;
  effects: number;
  max_input_units: number;
  max_output_tokens?: number;
}
export interface TextConversationInput {
  case_ref: string;
  participant_ref: string;
  thread_ref: string;
  submission_ref: string;
  expected_generation: number;
  parts: Array<ConversationTextPart>;
  intent?: ConversationIntent;
}
export interface ConversationResultSelection {
  selected_target_id: string;
}
export interface ConversationPrimaryResult {
  result_id: string;
  invocation_id: string;
  output: string;
  selection: ConversationResultSelection;
}
export type ConversationPosture = "admitted" | "running" | "completed" | "provider_result_recorded" | "refused" | "failed" | "cancelled" | "delivery_indeterminate" | "awaiting_review" | "budget_exhausted" | "unresolved";
export type CaseWorkPosture = "completed" | "awaiting_review" | "delivery_indeterminate" | "budget_exhausted" | "unresolved" | "cancelled_before_dispatch";
export interface CaseWorkStepObservation {
  ordinal: number;
  source_ref: string;
  selection_ref: string;
  target_ref: string;
  invocation_ref?: string | null;
  provider_result_ref?: string | null;
  operation_ref?: string | null;
  outcome_refs: Array<string>;
  operation?: CaseOperation;
  read_observation?: CaseReadObservation;
}
export interface CaseWorkObservation {
  schema: string;
  request_ref: string;
  participant_ref: string;
  thread_ref: string;
  observed_generation: number;
  posture: CaseWorkPosture;
  answer?: string | null;
  steps: Array<CaseWorkStepObservation>;
}
export interface AttemptObservation {
  outcome_id?: string;
  target_id?: string;
  attempt_number?: number;
  delivery?: string;
  stage?: string;
  request_bytes_written?: number;
  response_status?: number;
  no_execution_proven?: boolean;
  failure_class?: string;
  recorded_at_unix_ms?: number;
}
export interface ConversationObservation {
  case_ref: string;
  participant_ref: string;
  submission_ref: string;
  turn_ref: string;
  request_ref: string;
  identity?: ConversationIdentity;
  observed_generation: number;
  posture: ConversationPosture;
  invocation_refs: Array<string>;
  primary_result?: ConversationPrimaryResult | null;
  attempt_outcomes: Array<AttemptObservation>;
  work?: CaseWorkObservation;
  prepared_context?: PreparedContextObservation;
}
export type ConversationSubmissionIdentityPosture = "unavailable" | "retained" | "caller_verified_legacy";
export interface ConversationIdentity {
  original_submission_ref?: string | null;
  submission_posture: ConversationSubmissionIdentityPosture;
  author_participant_ref: string;
  executor_participant_ref: string;
  thread_ref: string;
}
export type ConversationRequestDomain = "cognitive_composition";
export interface ConversationRequestReference {
  domain: ConversationRequestDomain;
  request_ref: string;
}
export interface ConversationRequestGetInput {
  case_ref: string;
  participant_ref: string;
  execution: ConversationRequestReference;
  include_context: boolean;
}
export type ExecutionDiscoveryReference = { domain: "conversation"; submission_ref: string } | { domain: "cognitive_composition"; request_ref: string } | { domain: "cognitive_realization"; plan_ref: string } | { domain: "runtime_work"; submission_ref: string } | { domain: "resource_request"; submission_ref: string } | { domain: "controlled_effect"; operation_ref: string } | { domain: "source_acquisition"; source_ref: string; attempt: number };
export interface ExecutionDiscoveryInput {
  case_ref: string;
  participant_ref: string;
  limit: number;
}
export interface ExecutionDiscoveryEntry {
  execution: ExecutionDiscoveryReference;
  recorded_at_unix_ms: number;
}
export interface ExecutionDiscovery {
  schema: string;
  case_ref: string;
  participant_ref: string;
  generation: number;
  entries: Array<ExecutionDiscoveryEntry>;
  limit: number;
  scope: string;
}
export interface ProgressiveConversationInput {
  case_ref: string;
  participant_ref: string;
  thread_ref: string;
  submission_ref: string;
  expected_generation: number;
  parts: Array<ConversationTextPart>;
  intent?: ConversationIntent;
  memory_search_mode: MemorySearchMode;
  progressive_output: boolean;
}
export interface ConversationProgressInput {
  case_ref: string;
  participant_ref: string;
  request_ref: string;
  after_sequence: number;
  stream_ref?: string;
}
export type ConversationProgressAvailability = "live" | "ended" | "unavailable";
export type ConversationProgressKind = "accepted" | "preparing_context" | "provider_admitted" | "provider_dispatched" | "model_fragment" | "provider_completed" | "result_recorded" | "execution_ended" | "interrupted";
export interface ConversationProgressEvent {
  sequence: number;
  kind: ConversationProgressKind;
  observed_at_unix_ms: number;
  invocation_ref?: string | null;
  target_ref?: string | null;
  fragment?: string | null;
}
export interface ConversationProgressObservation {
  schema: string;
  case_ref: string;
  participant_ref: string;
  executor_participant_ref: string;
  thread_ref: string;
  turn_ref: string;
  request_ref: string;
  stream_ref?: string | null;
  availability: ConversationProgressAvailability;
  oldest_sequence: number;
  last_sequence: number;
  history_gap: boolean;
  events: Array<ConversationProgressEvent>;
  partial_output?: string | null;
  partial_output_limited: boolean;
  execution: ConversationObservation;
  current_invocation_ref?: string | null;
  current_target_ref?: string | null;
}
export type MemorySearchMode = "standard" | "fast";
export type ContextSelectionSource = "deterministic" | "system_one";
export interface TaskConversationInput {
  case_ref: string;
  participant_ref: string;
  thread_ref: string;
  submission_ref: string;
  expected_generation: number;
  parts: Array<ConversationTextPart>;
  intent?: ConversationIntent;
  memory_search_mode: MemorySearchMode;
}
export interface ContextContribution {
  family: string;
  entries: number;
  json_bytes: number;
}
export interface ContextPreparationObservation {
  schema: string;
  observation_id: string;
  case_id: string;
  case_generation: number;
  participant_id: string;
  working_state_id: string;
  source_turn_ref: string;
  source: ContextSelectionSource;
  reason: string;
  candidate_working_state_id: string;
  selected_entry_refs: Array<string>;
  omitted_items: number;
  omission_reasons: Record<string, number>;
  contributions: Array<ContextContribution>;
  semantic_unit_budget: number;
  selected_semantic_units: number;
  context_frame_bytes: number;
  rendered_content_chars: number;
  rendered_system_bytes: number;
  rendered_user_bytes: number;
  output_contract_bytes: number;
  instruction_bytes: number;
  navigation_ref?: string | null;
  finite_request_ref?: string | null;
  finite_result_ref?: string | null;
  finite_dispatch?: FiniteDispatchPosture | null;
  finite_binding_ref?: string | null;
  finite_qualification_ref?: string | null;
  finite_plan_ref?: string | null;
  finite_ranking?: FastSearchRanking | null;
  finite_navigation?: FastSearchNavigation | null;
  finite_distribution?: unknown | null;
  finite_producer?: FiniteProducerIdentity | null;
  finite_engine_generation?: number | null;
  finite_score_semantics?: string | null;
  finite_score_scale?: number | null;
  finite_scores: Array<FastSearchScore>;
  finite_token_count?: number | null;
  finite_model_forward_count?: number | null;
  finite_compute_nanoseconds?: number | null;
  finite_caller_nanoseconds?: number | null;
  preparation_nanoseconds: number;
}
export interface PreparedInvocationContext {
  invocation_ref: string;
  lineage: unknown;
  working_state?: unknown | null;
  projection?: unknown | null;
  frame?: unknown | null;
  input_observation?: unknown | null;
  unavailable_reason?: string | null;
  preparation?: ContextPreparationObservation;
}
export interface PreparedContextObservation {
  schema: string;
  observed_generation: number;
  total_invocations: number;
  omitted_invocations: number;
  invocations: Array<PreparedInvocationContext>;
}
export interface TextConversationSubmission {
  created: boolean;
  execution: ConversationObservation;
}
export type ConversationDomain = "conversation";
export interface ConversationExecutionReference {
  domain: ConversationDomain;
  submission_ref: string;
}
export interface ConversationGetInput {
  case_ref: string;
  participant_ref: string;
  execution: ConversationExecutionReference;
}
export interface ConversationContextGetInput {
  case_ref: string;
  participant_ref: string;
  execution: ConversationExecutionReference;
  include_context: boolean;
}
export interface ConversationWorkResumeInput {
  case_ref: string;
  participant_ref: string;
  submission_ref: string;
  observed_generation: number;
  progressive_output?: boolean;
}
export type ResultState = "success" | "partial" | "unauthorized" | "stale" | "core_pending" | "not_implemented" | "transport_unavailable" | "error";
export interface OperationError {
  code: string;
  message: string;
  safe_message: string;
  result_state: ResultState;
}
export interface OperationResult<T = unknown> {
  operation_ref: string;
  result_state: ResultState;
  correlation_ref: string;
  data?: T;
  error?: OperationError;
}
export interface CaseUpdate {
  protocol: string;
  event_ref: string;
  event_type: string;
  event_family: string;
  case_ref: string;
  generation: number;
  sequence: number;
  cursor: string;
  affected_views: Array<string>;
}
export interface GenerationCut {
  kind: GenerationCutKind;
  value: number;
}
export type GenerationCutKind = "generation";
export interface RecallBounds {
  candidates: number;
  events: number;
  relations: number;
  segments: number;
  expansion_depth: number;
  semantic_units: number;
  bytes: number;
}
export interface RecallQuery {
  schema: string;
  case_id: string;
  expected_generation: number;
  participant_id: string;
  at: GenerationCut;
  query: string;
  required_refs: Array<string>;
  bounds: RecallBounds;
}
export interface RecallInput {
  request: RecallQuery;
}
export interface RecallCandidate {
  source_ref: string;
  plane: string;
  score_micros: number;
  matched_terms: Array<string>;
}
export interface RecallTraceSummary {
  schema: string;
  trace_id: string;
  request_id: string;
  request: RecallQuery;
  generation: number;
  disclosure_digest: string;
  qualified_source_digest: string;
  closure_complete: boolean;
  omitted_candidates: number;
  expansion_stopped_at_depth: boolean;
  limitations: Array<string>;
  candidates: Array<RecallCandidate>;
}
export interface RecallSelection {
  trace: RecallTraceSummary;
}
export interface WorkflowInput {
  case_ref: string;
  node_ref: string;
  value: string;
}
export interface WorkflowAdoptPatchInput {
  case_ref: string;
  patch_ref: string;
}
export interface HandoffAcceptInput {
  target_case_ref: string;
  source_case_ref: string;
  handoff_ref: string;
  participant_ref: string;
}
export interface HandoffReconcileInput {
  source_case_ref: string;
  handoff_ref: string;
}
export interface ProcessAttachmentInput {
  case_ref: string;
  attachment_ref: string;
  pid: number;
  policy_owner_participant_ref: string;
  actions: Array<ProcessAction>;
  review_requirement: ReviewRequirement;
}
export type ProcessAction = "terminate" | "suspend" | "resume";
export type ReviewRequirement = "automatic" | "require_review";
export interface ProductGrant {
  valid_from_unix_ms?: number | null;
  valid_until_unix_ms?: number | null;
  max_major_version?: number | null;
  updates_until_unix_ms?: number | null;
  offline_until_unix_ms?: number | null;
}
export interface EntitlementClaim {
  schema: string;
  product: string;
  edition: string;
  holder_ref: string;
  issuer_ref: string;
  evidence_ref: string;
  installation_ref?: string | null;
  grants: Array<ProductGrant>;
}
export type EntitlementPosture = "missing" | "unverifiable" | "invalid" | "expired" | "not_yet_valid" | "version_not_covered" | "stale";
export interface EntitlementObservation {
  posture: EntitlementPosture;
  verification: string;
  access_granted: boolean;
  observed_at_unix_ms?: number | null;
  claim?: EntitlementClaim | null;
}
export interface ProductProfile {
  schema: string;
  profile_ref: string;
  installation_ref: string;
  principal_ref: string;
  selected_tenant_ref?: string | null;
  entitlement_claim?: EntitlementClaim | null;
  entitlement_observed_at_unix_ms?: number | null;
  local_development_enabled?: boolean;
  created_at_unix_ms: number;
  revision: number;
}
export type BootstrapPosture = "identity_required" | "profile_required" | "workspace_required" | "workspace_selection_required" | "workspace_unavailable" | "ready";
export interface ProductAccess {
  product: string;
  version: string;
  access_policy: string;
  license_verification: string;
}
export interface ProductAccount {
  posture: string;
  linkage?: string | null;
  reason: string;
  sign_in_supported: boolean;
  sign_out_supported: boolean;
}
export interface ProductPrincipal {
  posture: string;
  principal_ref?: string | null;
  authentication_method: string;
}
export interface ProductWorkspace {
  tenant_ref: string;
  display_name: string;
  kind: string;
  organization_ref: string;
  membership: string;
}
export interface ProductInitializeInput {
  create_personal_workspace: boolean;
}
export interface ProductWorkspaceSelectInput {
  tenant_ref: string;
  expected_revision: number;
}
export interface ProductEntitlementRecordInput {
  claim?: EntitlementClaim | null;
  expected_revision: number;
}
export interface ProductActivationStartInput {
  name: string;
}
export interface ProductActivationPollInput {
  activation_ref: string;
}
export type ProductLoginClient = "cli" | "studio";
export interface ProductLoginStartInput {
  client: ProductLoginClient;
  name: string;
}
export interface ProductLoginCancelInput {
  login_ref: string;
}
export type ProductLoginPosture = "idle" | "awaiting_browser" | "exchanging" | "authenticated" | "cancelled" | "expired" | "unavailable" | "refused" | "interrupted" | "indeterminate";
export type ProductLoginFailure = "service_unavailable" | "unsupported_contract" | "authorization_refused" | "entitlement_required" | "token_refused" | "entitlement_verification_refused" | "delivery_indeterminate" | "listener_interrupted" | "request_expired";
export interface ProductLoginObservation {
  schema: string;
  login_ref?: string | null;
  posture: ProductLoginPosture;
  authorization_url?: string | null;
  expires_at_unix_ms?: number | null;
  callback_received: boolean;
  failure?: ProductLoginFailure | null;
  auth: ProductAuthObservation;
}
export type CommercialSessionPosture = "signed_out" | "activation_pending" | "authenticated" | "credential_unavailable";
export type ActivationPosture = "pending" | "slow_down" | "activated" | "expired" | "denied" | "indeterminate";
export type CommercialServicePosture = "not_observed" | "reachable" | "unavailable" | "credential_rejected" | "entitlement_refused" | "unsupported_contract";
export type ProductAccessPosture = "trial_active" | "paid_active" | "not_yet_valid" | "expired" | "revoked" | "clock_rollback";
export type AcquiredAccessKind = "trial" | "subscription" | "team";
export type EntitlementVerificationRefusal = "malformed" | "unsupported_contract" | "unsupported_issuer" | "unsupported_key" | "invalid_signature" | "invalid_installation_binding" | "invalid_claims" | "unsupported_policy";
export type ProductPolicyScope = "installation" | "member" | "organization_pool";
export interface ProductAccessPolicy {
  schema: string;
  policy_id: string;
  revision: string;
  scope: ProductPolicyScope;
  owner_id: string;
  assignment_ref?: string | null;
  capabilities: Array<string>;
  limits: Record<string, number | null>;
}
export interface ProductActivationObservation {
  activation_ref: string;
  posture: ActivationPosture;
  user_code: string;
  verification_uri: string;
  verification_uri_complete: string;
  expires_at_unix_ms: number;
  poll_interval_ms: number;
  next_poll_at_unix_ms: number;
}
export interface VerifiedProductAccessObservation {
  schema: string;
  posture: ProductAccessPosture;
  licensed_operation_allowed: boolean;
  account_ref: string;
  commercial_installation_ref: string;
  grant_ref: string;
  attestation_ref: string;
  attestation_digest: string;
  issuer_ref: string;
  key_ref: string;
  kind: AcquiredAccessKind;
  issued_at_unix_ms: number;
  not_before_unix_ms: number;
  valid_until_unix_ms: number;
  offline_until_unix_ms: number;
  observed_at_unix_ms: number;
  plan_ref?: string;
  policy?: ProductAccessPolicy;
}
export interface ProductAuthObservation {
  schema: string;
  session: CommercialSessionPosture;
  service: CommercialServicePosture;
  account_ref?: string | null;
  commercial_installation_ref?: string | null;
  activation?: ProductActivationObservation | null;
  access?: VerifiedProductAccessObservation | null;
  verification_refusal?: EntitlementVerificationRefusal | null;
  online_access_refused: boolean;
  licensed_progress_allowed: boolean;
  credential_storage: string;
}
export interface ProductBootstrapProjection {
  schema: string;
  posture: BootstrapPosture;
  product: ProductAccess;
  account: ProductAccount;
  commercial_auth?: ProductAuthObservation | null;
  access?: ProductAccessSourceObservation;
  profile?: ProductProfile | null;
  local_home: string;
  principal: ProductPrincipal;
  entitlement: EntitlementObservation;
  workspaces: Array<ProductWorkspace>;
  selected_workspace_ref?: string | null;
  selected_workspace_available: boolean;
  external_prerequisites: Array<string>;
  case_authority: string;
}
export interface CaseListInput {
  tenant_id?: string;
}
export type CaseReadKind = "knowledge_search" | "recall" | "workflow_inspect";
export type CaseReadRequest = { read: "knowledge_search"; query: string; limit: number } | { read: "recall"; query: string; limit: number } | { read: "workflow_inspect" };
export type CaseReadResult = { kind: "knowledge"; view: KnowledgeView; hits: Array<KnowledgeHit> } | { kind: "recall"; trace: CanonicalRecallTrace } | { kind: "workflow"; definition: CaseWorkflowDefinition; resolution: CaseWorkflowResolution };
export interface CaseReadObservation {
  schema: string;
  observation_id: string;
  case_id: string;
  participant_id: string;
  request_id: string;
  thread_id: string;
  turn_id: string;
  provider_result_id: string;
  provider_invocation_id: string;
  provider_call_id: string;
  provider_function_name: string;
  observed_generation: number;
  request: CaseReadRequest;
  result: CaseReadResult;
}
export interface CanonicalRecallTrace {
  schema: string;
  trace_id: string;
  request_id: string;
  request: RecallQuery;
  generation: number;
  disclosure_digest: string;
  qualified_source_digest: string;
  events: Array<CanonicalRecallEvent>;
  relations: Array<CanonicalExperienceRelation>;
  segments: Array<CanonicalRecallSegment>;
  assertions: Array<CanonicalRecallAssertion>;
  contradictions: Array<CanonicalContradiction>;
  candidates: Array<RecallCandidate>;
  vector_evidence_digest?: string | null;
  source_closure: Array<CanonicalSourceClosure>;
  closure_complete: boolean;
  omitted_candidates: number;
  expansion_stopped_at_depth: boolean;
  limitations: Array<string>;
  documentary?: CanonicalDocumentaryTrace;
}
export type RecallSelectionReason = "exact_required_ref" | "current_state_anchor" | "lexical_candidate" | "vector_candidate" | "qualified_relation_expansion" | "source_closure" | "supersession_chain" | "contradiction_context";
export interface CanonicalRecallEvent {
  event: CanonicalExperienceEvent;
  label: string;
  validity_at_cut: string;
  reasons: Array<RecallSelectionReason>;
  content_reference?: RecallContentReference;
  resource_reference?: string;
}
export interface CanonicalExperienceEvent {
  transition_id: string;
  kind: string;
  object_refs: Array<string>;
  posture: string;
  recorded_generation: number;
  recorded_at_unix_ms?: number | null;
  observed_at_unix_ms?: number | null;
  occurred_at_unix_ms?: number | null;
  source_closed: boolean;
}
export interface RecallContentReference {
  admission_id: string;
  object_id: string;
  source_resource_id: string;
  source_path: string;
}
export interface CanonicalExperienceRelation {
  relation_id: string;
  from_event: string;
  to_event: string;
  kind: string;
  posture: string;
  known_at_generation: number;
  sources: Array<CanonicalRelationSource>;
}
export interface CanonicalRelationSource {
  transition_id: string;
  field: string;
}
export interface CanonicalRecallSegment {
  segment_id: string;
  events: Array<string>;
  grouping: string;
}
export interface CanonicalRecallAssertion {
  assertion: CanonicalMemoryAssertion;
  source_events: Array<string>;
  reasons: Array<RecallSelectionReason>;
}
export interface CanonicalMemoryAssertion {
  schema: string;
  assertion_id: string;
  case_id: string;
  semantic_schema_version: string;
  subject: unknown;
  predicate: string;
  value: unknown;
  epistemic_class: string;
  support_refs: Array<unknown>;
  source_generation_start: number;
  source_generation_end: number;
  origin: string;
  lifecycle: string;
  contradiction_set_ref?: string | null;
  supersession_refs: Array<string>;
  participant_refs: Array<string>;
  assertion_digest: string;
}
export interface CanonicalContradiction {
  schema: string;
  contradiction_id: string;
  case_id: string;
  subject: unknown;
  predicate: string;
  competing_assertion_ids: Array<string>;
  contradiction_kind: string;
  resolution_posture: string;
  mechanical_basis: string;
  derivation_version: string;
}
export interface CanonicalSourceClosure {
  source_ref: string;
  posture: string;
}
export interface CanonicalDocumentaryTrace {
  sources: Array<RecalledDocumentSource>;
  units: Array<RecalledDocumentUnit>;
  relations: Array<KnowledgeRelation>;
  cross_references: Array<RecallDocumentCrossReference>;
  contradictions: Array<RecallKnowledgeConflict>;
  segments: Array<RecallDocumentSegment>;
}
export interface RecalledDocumentSource {
  source: KnowledgeSource;
  admitted_at_generation: number;
  admission_transition: string;
  applicable_at_cut: boolean;
  reasons: Array<RecallSelectionReason>;
}
export interface RecalledDocumentUnit {
  unit: KnowledgeUnit;
  reasons: Array<RecallSelectionReason>;
}
export interface RecallDocumentCrossReference {
  unit: string;
  exact_reference: string;
  event: string;
  posture: string;
}
export interface RecallKnowledgeConflict {
  id: string;
  entity: string;
  predicate: string;
  members: Array<string>;
  posture: string;
}
export interface RecallDocumentSegment {
  source: string;
  units: Array<string>;
  grouping: string;
}
export interface CaseWorkflowDefinition {
  schema: string;
  workflow_definition_id: string;
  content_digest: string;
  integrity_digest: string;
  tenant_id: string;
  workflow_key: string;
  declared_version: string;
  name: string;
  description: string;
  nodes: Array<unknown>;
  edges: Array<unknown>;
  created_by_principal_id: string;
  created_at_unix_ms: number;
}
export interface CaseWorkflowResolution {
  schema: string;
  tenant_id: string;
  case_id: string;
  case_generation: number;
  workflow_definition_id: string;
  workflow_binding_id: string;
  effective_nodes: Array<unknown>;
  effective_edges: Array<unknown>;
  effective_revision: number;
  effective_topology_digest: string;
  amendment_ids: Array<string>;
  referenced_definition_ids: Array<string>;
  nodes: Array<CaseWorkflowNodeResolution>;
  ready_work: Array<CaseWorkflowReadyWork>;
  satisfied_count: number;
  skipped_count: number;
  active_count: number;
  waiting_count: number;
  completed: boolean;
}
export interface CaseWorkflowNodeResolution {
  node_id: string;
  node_kind: string;
  posture: string;
  reason: string;
  execution_id?: string | null;
  evidence_refs: Array<string>;
}
export interface CaseWorkflowReadyWork {
  node_id: string;
  node_kind: string;
  topological_rank: number;
}
export interface OperationScope {
  case_id: string;
  participant_refs: Array<string>;
  resource_refs: Array<string>;
  policy_refs: Array<string>;
}
export type ResourceAccessKind = "filesystem_read" | "filesystem_search" | "discover" | "admit_content" | "content_read" | "process_run" | "database_query" | "database_mutation" | "http_fetch" | "mcp_catalog" | "mcp_resource_read" | "mcp_tool_call" | "web_search";
export type OperationKind = "filesystem_write" | "process_signal" | { resource_access: ResourceAccessKind };
export type OperationOrigin = { kind: "participant_request"; request_id: string; principal_id: string; participant_link_id: string } | { kind: "provider_result"; provider_result_id: string; provider_invocation_id: string } | { kind: "compatibility_review"; review_id: string; attempt_id: string } | { kind: "workflow_deterministic_proposal"; proposal_id: string; workflow_execution_id: string };
export interface FilesystemWritePayload {
  relative_path: string;
  content: string;
  content_digest: string;
  content_bytes: number;
  baseline_observation_ref?: string;
}
export interface MaterialInspectInput {
  case_ref: string;
  participant_ref: string;
  operation_ref: string;
  source_ref?: string;
}
export interface MaterialReadEvidence {
  observation_ref: string;
  operation_ref: string;
  decision_ref: string;
  resource_ref: string;
  configuration_digest: string;
  relative_path: string;
  content_digest: string;
  content_bytes: number;
  observed_at_unix_ms: number;
  file_identity?: MaterialFileIdentity | null;
}
export type MaterialSourcePosture = "unverified" | "retained_scope_content_match" | "unavailable";
export type MaterialBaselinePosture = "unavailable" | "bound_read" | "observed_read" | "prepare_only";
export type MaterialEffectPosture = "proposed" | "observed" | "review_pending" | "denied" | "prepared" | "applied_attested" | "uncertain" | "finalized_not_applied";
export interface MaterialSourceRelationship {
  source_ref: string;
  revision_ref?: string | null;
  material_revision_ref?: string | null;
  source_resource_ref?: string | null;
  source_configuration_digest?: string | null;
  posture: MaterialSourcePosture;
  reason: string;
}
export type MaterialFilesystemState = "absent" | "file" | "directory" | "symlink" | "other" | "unavailable";
export interface MaterialFilesystemObservation {
  schema: string;
  observation_id: string;
  resource_attachment_id: string;
  relative_path: string;
  state: MaterialFilesystemState;
  content_digest?: string;
  size_bytes?: number;
  error?: string;
  observed_at_unix_ms: number;
  file_identity?: MaterialFileIdentity;
}
export interface MaterialFileIdentity {
  device: number;
  inode: number;
  modified_seconds: number;
  modified_nanos: number;
  changed_seconds: number;
  changed_nanos: number;
}
export type MaterialReceiptOutcome = "applied" | "already_applied" | "no_effect" | "failed_no_effect" | "conflict" | "indeterminate";
export interface MaterialEffectReceipt {
  schema: string;
  receipt_id: string;
  effect_id: string;
  operation_id: string;
  decision_id: string;
  grant_id: string;
  resource_attachment_id: string;
  relative_path: string;
  pre_observation_id: string;
  post_observation_id: string;
  outcome: MaterialReceiptOutcome;
  carrier_backend: string;
  carrier_attempted: boolean;
  mutation_performed: boolean;
  completed_at_unix_ms: number;
}
export interface MaterialProvenanceObservation {
  schema: string;
  case_ref: string;
  participant_ref: string;
  operation_ref: string;
  operation_digest: string;
  observed_generation: number;
  resource_ref: string;
  configuration_digest?: string | null;
  resource_control_ref?: string | null;
  root_identity_digest?: string | null;
  relative_path: string;
  origin: OperationOrigin;
  proposed_content_digest?: string | null;
  baseline_posture: MaterialBaselinePosture;
  baseline?: MaterialReadEvidence | null;
  posture: MaterialEffectPosture;
  decision_refs: Array<string>;
  review_refs: Array<string>;
  effect_ref?: string | null;
  grant_ref?: string | null;
  pre_observation?: MaterialFilesystemObservation | null;
  post_observation?: MaterialFilesystemObservation | null;
  receipt?: MaterialEffectReceipt | null;
  source?: MaterialSourceRelationship | null;
  freshness: string;
}
export interface ProcessSignalPayload {
  action: ProcessSignalAction;
  target_identity_digest: string;
}
export type ProcessSignalAction = "terminate" | "suspend" | "resume";
export type ResourceAction = { action: "filesystem_read"; path: string } | { action: "filesystem_search"; path: string; needle: string } | { action: "discover"; path: string } | { action: "admit_content"; path: string; candidate_digest: string } | { action: "content_read"; admission_id: string } | { action: "process_run"; name: string } | { action: "database_query"; name: string } | { action: "database_mutation"; name: string } | { action: "http_fetch"; name: string } | { action: "mcp_catalog" } | { action: "mcp_resource_read"; uri: string; catalog_digest: string } | { action: "mcp_tool_call"; name: string; catalog_digest: string; arguments: unknown } | { action: "web_search"; query: string; limit: number };
export interface ResourceRequest {
  schema: string;
  configuration_digest: string;
  action: ResourceAction;
}
export interface CaseOperation {
  schema: string;
  operation_id: string;
  operation_digest: string;
  case_id: string;
  participant_id: string;
  scope: OperationScope;
  kind: OperationKind;
  resource_attachment_id: string;
  filesystem_write: FilesystemWritePayload;
  process_signal?: ProcessSignalPayload;
  resource_request?: ResourceRequest;
  origin: OperationOrigin;
  expected_case_generation: number;
}
export type KnowledgeSourceBacking = { kind: "policy"; source_id: string; artifact_id: string } | { kind: "content"; admission_id: string } | { kind: "observation"; observation_id: string };
export type KnowledgeSourceRole = "policy" | "knowledge" | "operational";
export interface KnowledgeEntity {
  id: string;
  definitions: Array<string>;
}
export interface KnowledgeTopic {
  name: string;
  units: Array<string>;
}
export type WebSearchProvider = "tavily";
export interface WebSearchHit {
  title: string;
  url: string;
  snippet: string;
  relevance_score?: number | null;
}
export interface WebSearchResult {
  schema: string;
  provider: WebSearchProvider;
  query: string;
  provider_request_id?: string | null;
  response_body_digest: string;
  provider_response_seconds?: number | null;
  hits: Array<WebSearchHit>;
  posture: string;
}
export type ResourceReviewRequirement = "automatic" | "require_review";
export interface NetworkResourceInput {
  endpoint: string;
  allowed_ip_addresses: Array<string>;
  credential_ref?: string | null;
}
export interface ResourceProcessRunnerInput {
  executable: string;
  executable_digest: string;
  argv: Array<string>;
  working_directory: string;
  environment: Record<string, string>;
  timeout_ms: number;
}
export type ResourceAddressInput = { kind: "filesystem"; root: string } | { kind: "discovery"; root: string } | { kind: "process_runner"; root: string; runners: Record<string, ResourceProcessRunnerInput> } | { kind: "sqlite"; root: string; path: string; queries: Record<string, string> } | { kind: "http_service"; endpoint: NetworkResourceInput; paths: Record<string, string> } | { kind: "search_api"; provider: WebSearchProvider; endpoint: NetworkResourceInput } | { kind: "mcp"; endpoint: NetworkResourceInput };
export interface ResourceDefinitionInput {
  schema: "yai.resource_definition.v1";
  attachment_id: string;
  policy_owner: string;
  participant_ids: Array<string>;
  operations: Array<ResourceAccessKind>;
  read_prefixes: Array<string>;
  names: Array<string>;
  max_output_bytes: number;
  max_items: number;
  address: ResourceAddressInput;
  write_prefix?: string;
  max_write_bytes?: number;
  review_requirement?: ResourceReviewRequirement;
}
export interface ResourceImportInput {
  case_ref: string;
  definition: ResourceDefinitionInput;
}
