// Generated by tools/workflows.py; edit contract/workflows.json.
export interface EmptyInput {
}
export interface CaseRefInput {
  case_ref: string;
}
export interface CaseCreateInput {
  tenant_id: string;
  case_ref: string;
}
export interface IdentityBootstrapInput {
  tenant_id: string;
  organization_ref: string;
}
export interface TenantInput {
  tenant_id: string;
}
export interface ParticipantRoleInput {
  case_ref: string;
  participant_ref: string;
  role: string;
}
export interface ReviewResolveInput {
  case_ref: string;
  review_ref: string;
  participant_ref?: string | null;
  reason: string;
}
export interface MaterialReadInput {
  case_ref: string;
  source_ref: string;
  revision_ref?: string | null;
  path: string;
  expected_generation?: number | null;
}
export interface MaterialReadResult {
  case_ref: string;
  generation: number;
  source_ref: string;
  revision_ref: string;
  path: string;
  digest: string;
  bytes: number;
  media_type: string;
  encoding: string;
  content: string;
}
export interface ReviewActionProjection {
  schema: string;
  action_id: string;
  integrity_digest: string;
  review_id: string;
  operation_id: string;
  case_id: string;
  reviewer_participant_id: string;
  principal_id?: string | null;
  tenant_id?: string | null;
  action: string;
  reason: string;
  expected_case_generation: number;
  source: string;
}
export interface ReviewResolveResult {
  review_ref: string;
  action: ReviewActionProjection;
  effective_decision_ref?: string | null;
  state: CaseVersionProjection;
  external_effect: boolean;
}
export interface PrincipalProjection {
  principal_id: string;
  authentication_method: string;
}
export interface TenantProjection {
  tenant_id: string;
  organization_ref: string;
}
export interface TenantMembershipProjection {
  membership: string;
  tenant: TenantProjection;
}
export interface AuthenticationProjection {
  binding_ref: string;
}
export interface IdentityPresentation {
  principal: PrincipalProjection;
  tenants: Array<TenantMembershipProjection>;
  authentication: AuthenticationProjection;
}
export interface KnowledgeRequest {
  case_id: string;
  source?: string | null;
  revision?: string | null;
  max_units: number;
}
export interface KnowledgeInspectInput {
  request: KnowledgeRequest;
}
export interface KnowledgeSearchInput {
  request: KnowledgeRequest;
  query: string;
  limit: number;
}
export interface KnowledgeResolveInput {
  request: KnowledgeRequest;
  unit_ref: string;
}
export interface KnowledgeUnit {
  id: string;
  source: string;
  text: string;
  kind: string;
  posture: string;
}
export interface KnowledgeSource {
  id: string;
  path: string;
}
export interface KnowledgeRelation {
  id: string;
  from: string;
  to: string;
  kind: string;
}
export interface KnowledgeView {
  id: string;
  case_id: string;
  units: Array<KnowledgeUnit>;
  sources: Array<KnowledgeSource>;
  relations: Array<KnowledgeRelation>;
}
export interface KnowledgeHit {
  document_id: string;
  score_micros: number;
  matched_terms: Array<string>;
}
export interface KnowledgeSearchResult {
  view: KnowledgeView;
  hits: Array<KnowledgeHit>;
}
export interface KnowledgeResolveResult {
  view: KnowledgeView;
  unit: KnowledgeUnit;
}
export interface KnowledgeNavigationResult {
  view_ref: string;
  navigation: string;
}
export interface CaseVersionProjection {
  case_id: string;
  generation: number;
}
export interface WorkCommit {
  state: CaseVersionProjection;
  transition: TransitionReceipt;
}
export interface TransitionReceipt {
  transition_id: string;
  payload: TransitionReceiptPayload;
}
export interface TransitionReceiptPayload {
  kind: string;
  data: TransitionReceiptData;
}
export interface TransitionReceiptData {
  patch?: WorkflowPatchReceipt | null;
  offer?: HandoffOfferReceipt | null;
  acceptance?: HandoffReceipt | null;
  decline?: HandoffReceipt | null;
  result?: HandoffReceipt | null;
  reconciliation?: HandoffReceipt | null;
}
export interface WorkflowPatchReceipt {
  patch_id: string;
  base_effective_topology_digest: string;
}
export interface HandoffOfferReceipt {
  handoff_id: string;
  source_case_id: string;
  target_case_id: string;
}
export interface HandoffReceipt {
  handoff_id: string;
}
export interface CaseSummary {
  case_ref: string;
  display_name: string;
  case_status: string;
  generation: number;
  updated_at_unix_ms?: number | null;
  participant_count: number;
  source_count: number;
  resource_count: number;
  pending_review_count: number;
}
export interface CaseListProjection {
  cases: Array<CaseSummary>;
  authority: string;
}
export interface CaseAttachment {
  case_ref: string;
  case_status: string;
  generation: number;
  authenticated_principal: string;
  participant_ref: string;
  thread_ref?: string | null;
  attachment: "ephemeral";
}
export interface ApplicationCatalog {
  schema: "yai.application_capability_catalog.v1";
  application_protocol: string;
  operations: Array<ApplicationOperation>;
  capabilities: Array<ApplicationCapability>;
}
export interface ApplicationOperation {
  operation_id: string;
  meaning: string;
  input_contract: string;
  output_contract: string;
  impact: string;
  authority: string;
}
export interface ApplicationCapability {
  capability_id: string;
  meaning: string;
  application_posture: "ready" | "deferred" | "not_applicable";
  application_operation_ids: Array<string>;
  application_deferred_reason?: string | null;
  studio_posture: string;
}
export interface ParticipantLinkInput {
  case_ref: string;
  participant_ref: string;
  principal_ref: string;
}
export interface StateMutationReceipt {
  changed: boolean;
  transition_ref?: string | null;
  state: CaseVersionProjection;
}
export interface RegisteredModelsInput {
  tenant_id: string;
  target_ref: string;
}
export interface ModelInventory {
  target_ref?: string | null;
  observed_at_unix_ms?: number | null;
  models: Array<string>;
  scope: string;
  authority: string;
}
export interface ConversationTextPart {
  modality: TextModality;
  media_type: string;
  bytes: Array<number>;
}
export type TextModality = "text";
export type ContextDepth = "focused";
export interface ConversationIntent {
  context_depth: ContextDepth;
}
export interface TextConversationInput {
  case_ref: string;
  participant_ref: string;
  thread_ref: string;
  submission_ref: string;
  expected_generation: number;
  parts: Array<ConversationTextPart>;
  intent?: ConversationIntent | null;
}
export interface ConversationResultSelection {
  selected_target_id: string;
}
export interface ConversationPrimaryResult {
  result_id: string;
  invocation_id: string;
  output: string;
  selection: ConversationResultSelection;
}
export type ConversationPosture = "admitted" | "running" | "completed" | "provider_result_recorded" | "refused" | "failed" | "cancelled" | "delivery_indeterminate" | "unresolved";
export interface AttemptObservation {
  outcome_id?: string | null;
  target_id?: string | null;
  attempt_number?: number | null;
  delivery?: string | null;
  stage?: string | null;
  request_bytes_written?: number | null;
  response_status?: number | null;
  no_execution_proven?: boolean | null;
  failure_class?: string | null;
  recorded_at_unix_ms?: number | null;
}
export interface ConversationObservation {
  case_ref: string;
  participant_ref: string;
  submission_ref: string;
  turn_ref: string;
  request_ref: string;
  observed_generation: number;
  posture: ConversationPosture;
  invocation_refs: Array<string>;
  primary_result?: ConversationPrimaryResult | null;
  attempt_outcomes: Array<AttemptObservation>;
}
export interface TextConversationSubmission {
  created: boolean;
  execution: ConversationObservation;
}
export type ConversationDomain = "conversation";
export interface ConversationExecutionReference {
  domain: ConversationDomain;
  submission_ref: string;
}
export interface ConversationGetInput {
  case_ref: string;
  participant_ref: string;
  execution: ConversationExecutionReference;
}
export type ResultState = "success" | "partial" | "unauthorized" | "stale" | "core_pending" | "not_implemented" | "transport_unavailable" | "error";
export interface OperationError {
  code: string;
  message: string;
  safe_message: string;
  result_state: ResultState;
}
export interface OperationResult<T = unknown> {
  operation_ref: string;
  result_state: ResultState;
  correlation_ref: string;
  data?: T | null;
  error?: OperationError | null;
}
export interface CaseUpdate {
  protocol: string;
  event_ref: string;
  event_type: string;
  event_family: string;
  case_ref: string;
  generation: number;
  sequence: number;
  cursor: string;
  affected_views: Array<string>;
}
export interface GenerationCut {
  kind: GenerationCutKind;
  value: number;
}
export type GenerationCutKind = "generation";
export interface RecallBounds {
  candidates: number;
  events: number;
  relations: number;
  segments: number;
  expansion_depth: number;
  semantic_units: number;
  bytes: number;
}
export interface RecallQuery {
  schema: string;
  case_id: string;
  expected_generation: number;
  participant_id: string;
  at: GenerationCut;
  query: string;
  required_refs: Array<string>;
  bounds: RecallBounds;
}
export interface RecallInput {
  request: RecallQuery;
}
export interface RecallCandidate {
  source_ref: string;
  plane: string;
  score_micros: number;
  matched_terms: Array<string>;
}
export interface RecallTraceSummary {
  schema: string;
  trace_id: string;
  request_id: string;
  request: RecallQuery;
  generation: number;
  disclosure_digest: string;
  qualified_source_digest: string;
  closure_complete: boolean;
  omitted_candidates: number;
  expansion_stopped_at_depth: boolean;
  limitations: Array<string>;
  candidates: Array<RecallCandidate>;
}
export interface RecallSelection {
  trace: RecallTraceSummary;
}
export interface WorkflowInput {
  case_ref: string;
  node_ref: string;
  value: string;
}
export interface WorkflowAdoptPatchInput {
  case_ref: string;
  patch_ref: string;
}
export interface HandoffAcceptInput {
  target_case_ref: string;
  source_case_ref: string;
  handoff_ref: string;
  participant_ref: string;
}
export interface HandoffReconcileInput {
  source_case_ref: string;
  handoff_ref: string;
}
export interface ProcessAttachmentInput {
  case_ref: string;
  attachment_ref: string;
  pid: number;
  policy_owner_participant_ref: string;
  actions: Array<ProcessAction>;
  review_requirement: ReviewRequirement;
}
export type ProcessAction = "terminate" | "suspend" | "resume";
export type ReviewRequirement = "automatic" | "require_review";
