#!/usr/bin/env python3
"""Project the public workflow contract; --check refuses stale public surfaces."""
import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def render(contract):
    if contract['format'] != 'yai.sdk.workflow-contract.v1':
        raise ValueError('unsupported workflow contract')
    types = contract['types']
    if not set(contract['closed_types']) <= set(types):
        raise ValueError('unknown closed type')
    generics = contract.get('generics', {})

    def ty(value, language):
        if ':' in value:
            kind, nested = value.split(':', 1)
            inner = ty(nested, language)
            if kind == 'array':
                return f'Vec<{inner}>' if language == 'rust' else f'Array<{inner}>'
            if kind in ('optional', 'nullable'):
                return f'Option<{inner}>' if language == 'rust' else (inner if kind == 'optional' else f'{inner} | null')
            raise ValueError(f'unknown type constructor: {kind}')
        primitives = {'string': ('String', 'string'), 'u8': ('u8', 'number'), 'u64': ('u64', 'number'),
                      'usize': ('usize', 'number'), 'u16': ('u16', 'number'), 'u32': ('u32', 'number'), 'i64': ('i64', 'number'), 'bool': ('bool', 'boolean'),
                      'json': ('serde_json::Value', 'unknown'), 'T': ('serde_json::Value', 'T')}
        if value in primitives:
            return primitives[value][language == 'typescript']
        if value not in types:
            raise ValueError(f'unknown public type: {value}')
        return value

    rust = ['// Generated by tools/workflows.py; edit contract/workflows.json.',
            'use serde::{Deserialize, Serialize};']
    ts = ['// Generated by tools/workflows.py; edit contract/workflows.json.']
    for name, fields in types.items():
        if not re.fullmatch('[A-Z][A-Za-z0-9]*', name):
            raise ValueError('invalid public type name')
        if '$enum' in fields:
            values = fields['$enum']
            if not values or len(set(values)) != len(values):
                raise ValueError('empty or duplicate enum values')
            rust.append('#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]')
            rust.append(f'pub enum {name} {{')
            for index, value in enumerate(values):
                if not re.fullmatch('[a-z][a-z0-9_]*', value):
                    raise ValueError('invalid enum value')
                if index == 0:
                    rust.append('    #[default]')
                rust.extend([f'    #[serde(rename = "{value}")]',
                             '    ' + ''.join(part.title() for part in value.split('_')) + ','])
            rust.append('}')
            ts.append(f'export type {name} = ' + ' | '.join(json.dumps(value) for value in values) + ';')
            continue
        rust.append('#[derive(Clone, Debug, Default, Serialize, Deserialize)]')
        if name in contract['closed_types']:
            rust.append('#[serde(deny_unknown_fields)]')
        parameter = generics.get(name)
        if parameter not in (None, 'T'):
            raise ValueError('unsupported generic parameter')
        rust_name = name
        ts_name = name + ('<T = unknown>' if parameter else '')
        rust.append(f'pub struct {rust_name} {{')
        ts.append(f'export interface {ts_name} {{')
        for field, kind in fields.items():
            if not re.fullmatch('[a-z][a-z0-9_]*', field):
                raise ValueError('invalid public field')
            optional = kind.startswith('optional:')
            if optional:
                rust.append('    #[serde(default, skip_serializing_if = "Option::is_none")]')
            rust.append(f'    pub {field}: {ty(kind, "rust")},')
            ts_optional = optional or kind.startswith('nullable:')
            ts_type = ty(kind, 'typescript')
            values = contract.get('typescript_constraints', {}).get(name, {}).get(field)
            if values:
                if kind != 'string':
                    raise ValueError('literal constraint requires string')
                ts_type = ' | '.join(json.dumps(v) for v in values)
            ts.append(f'  {field}{"?" if ts_optional else ""}: {ts_type};')
        rust.append('}')
        ts.append('}')
    families = {}
    ids = set()
    methods = set()
    for op in contract['operations']:
        if op['id'] in ids:
            raise ValueError('duplicate operation identity')
        ids.add(op['id'])
        for key in ('family', 'method'):
            if not re.fullmatch('[a-z][a-z0-9_]*', op[key]):
                raise ValueError('invalid operation identifier')
        pair = (op['family'], op['method'])
        if pair in methods:
            raise ValueError('duplicate workflow method')
        methods.add(pair)
        for key in ('input', 'output'):
            ty(op[key], 'rust')
        families.setdefault(op['family'], []).append(op)
    rust.append('use crate::{ClientTransport, client::{Client, Error, Operation, Response}};')
    for family, operations in families.items():
        name = family.title()
        rust.extend([f'pub struct {name}<\'a, T>(pub(crate) &\'a Client<T>);',
                     f'impl<T: ClientTransport> Client<T> {{',
                     f'    pub fn {family}(&self) -> {name}<\'_, T> {{ {name}(self) }}', '}'])
        for op in operations:
            opname = name + ''.join(part.title() for part in op['method'].split('_'))
            rust.extend(['#[derive(Serialize)]', '#[serde(transparent)]',
                         f'struct {opname}<\'a>(&\'a {op["input"]});',
                         f'impl Operation for {opname}<\'_> {{',
                         f'    type Output = {op["output"]};',
                         f'    const ID: &\'static str = "{op["id"]}";',
                         f'    const INPUT_CONTRACT: Option<&\'static str> = Some("{op["input_contract"]}");',
                         f'    const OUTPUT_CONTRACT: Option<&\'static str> = Some("{op["output_contract"]}");', '}'])
            rust.extend([f'impl<T: ClientTransport> {name}<\'_, T> {{',
                         f'    pub fn {op["method"]}(&self, correlation: &str, input: &{op["input"]}) -> Result<Response<{op["output"]}>, Error> {{',
                         f'        self.0.execute(correlation, &{opname}(input))', '    }', '}'])
    return '\n'.join(rust) + '\n', '\n'.join(ts) + '\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    contract = json.loads((ROOT / 'contract/workflows.json').read_text())
    catalog = json.loads((ROOT / 'contract/operations.json').read_text())
    manual = (ROOT / 'typescript/projections.ts').read_text()
    collisions = set(re.findall(r'export (?:interface|type) (\w+)', manual)) & set(contract['types'])
    if collisions:
        raise SystemExit(f'duplicate public contract owners: {sorted(collisions)}')
    operations = {op['operation_id']: op for op in catalog['operations']}
    for op in contract['operations']:
        admitted = operations[op['id']]
        for identity in ('input_contract', 'output_contract'):
            if op[identity] != admitted[identity]:
                raise SystemExit(f'operation contract drift: {op["id"]} {identity}')
    outputs = render(contract)
    for relative, text in zip(('src/workflows.rs', 'typescript/workflows.ts'), outputs):
        path = ROOT / relative
        if args.check:
            if not path.is_file() or path.read_text() != text:
                raise SystemExit(f'stale workflow projection: {relative}')
        else:
            path.write_text(text)
    print(f'workflow contract: PASS {len(contract["types"])} types, {len(contract["operations"])} operations')


if __name__ == '__main__':
    main()
