// Generated by tools/workflows.py; edit contract/workflows.json.
use serde::{Deserialize, Serialize};
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct EmptyInput {
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct CaseRefInput {
    pub case_ref: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct CaseCreateInput {
    pub tenant_id: String,
    pub case_ref: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct IdentityBootstrapInput {
    pub tenant_id: String,
    pub organization_ref: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct TenantInput {
    pub tenant_id: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ParticipantRoleInput {
    pub case_ref: String,
    pub participant_ref: String,
    pub role: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ReviewResolveInput {
    pub case_ref: String,
    pub review_ref: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub participant_ref: Option<String>,
    pub reason: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct MaterialReadInput {
    pub case_ref: String,
    pub source_ref: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub revision_ref: Option<String>,
    pub path: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expected_generation: Option<u64>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct MaterialReadResult {
    pub case_ref: String,
    pub generation: u64,
    pub source_ref: String,
    pub revision_ref: String,
    pub path: String,
    pub digest: String,
    pub bytes: u64,
    pub media_type: String,
    pub encoding: String,
    pub content: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ReviewActionProjection {
    pub schema: String,
    pub action_id: String,
    pub integrity_digest: String,
    pub review_id: String,
    pub operation_id: String,
    pub case_id: String,
    pub reviewer_participant_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub principal_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<String>,
    pub action: String,
    pub reason: String,
    pub expected_case_generation: u64,
    pub source: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ReviewResolveResult {
    pub review_ref: String,
    pub action: ReviewActionProjection,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub effective_decision_ref: Option<String>,
    pub state: CaseVersionProjection,
    pub external_effect: bool,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct PrincipalProjection {
    pub principal_id: String,
    pub authentication_method: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct TenantProjection {
    pub tenant_id: String,
    pub organization_ref: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct TenantMembershipProjection {
    pub membership: String,
    pub tenant: TenantProjection,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct AuthenticationProjection {
    pub binding_ref: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct IdentityPresentation {
    pub principal: PrincipalProjection,
    pub tenants: Vec<TenantMembershipProjection>,
    pub authentication: AuthenticationProjection,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct KnowledgeRequest {
    pub case_id: String,
    pub source: Option<String>,
    pub revision: Option<String>,
    pub max_units: usize,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct KnowledgeInspectInput {
    pub request: KnowledgeRequest,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct KnowledgeSearchInput {
    pub request: KnowledgeRequest,
    pub query: String,
    pub limit: usize,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct KnowledgeResolveInput {
    pub request: KnowledgeRequest,
    pub unit_ref: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct KnowledgeUnit {
    pub id: String,
    pub source: String,
    pub text: String,
    pub kind: String,
    pub posture: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct KnowledgeSource {
    pub id: String,
    pub path: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct KnowledgeRelation {
    pub id: String,
    pub from: String,
    pub to: String,
    pub kind: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct KnowledgeView {
    pub id: String,
    pub case_id: String,
    pub units: Vec<KnowledgeUnit>,
    pub sources: Vec<KnowledgeSource>,
    pub relations: Vec<KnowledgeRelation>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct KnowledgeHit {
    pub document_id: String,
    pub score_micros: i64,
    pub matched_terms: Vec<String>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct KnowledgeSearchResult {
    pub view: KnowledgeView,
    pub hits: Vec<KnowledgeHit>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct KnowledgeResolveResult {
    pub view: KnowledgeView,
    pub unit: KnowledgeUnit,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct KnowledgeNavigationResult {
    pub view_ref: String,
    pub navigation: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CaseVersionProjection {
    pub case_id: String,
    pub generation: u64,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct WorkCommit {
    pub state: CaseVersionProjection,
    pub transition: TransitionReceipt,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct TransitionReceipt {
    pub transition_id: String,
    pub payload: TransitionReceiptPayload,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct TransitionReceiptPayload {
    pub kind: String,
    pub data: TransitionReceiptData,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct TransitionReceiptData {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub patch: Option<WorkflowPatchReceipt>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub offer: Option<HandoffOfferReceipt>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub acceptance: Option<HandoffReceipt>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub decline: Option<HandoffReceipt>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub result: Option<HandoffReceipt>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reconciliation: Option<HandoffReceipt>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct WorkflowPatchReceipt {
    pub patch_id: String,
    pub base_effective_topology_digest: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct HandoffOfferReceipt {
    pub handoff_id: String,
    pub source_case_id: String,
    pub target_case_id: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct HandoffReceipt {
    pub handoff_id: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct CaseSummary {
    pub case_ref: String,
    pub display_name: String,
    pub case_status: String,
    pub generation: u64,
    pub updated_at_unix_ms: Option<u64>,
    pub participant_count: usize,
    pub source_count: usize,
    pub resource_count: usize,
    pub pending_review_count: usize,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct CaseListProjection {
    pub cases: Vec<CaseSummary>,
    pub authority: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct CaseAttachment {
    pub case_ref: String,
    pub case_status: String,
    pub generation: u64,
    pub authenticated_principal: String,
    pub participant_ref: String,
    pub thread_ref: Option<String>,
    pub attachment: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ApplicationCatalog {
    pub schema: String,
    pub application_protocol: String,
    pub operations: Vec<ApplicationOperation>,
    pub capabilities: Vec<ApplicationCapability>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ApplicationOperation {
    pub operation_id: String,
    pub meaning: String,
    pub input_contract: String,
    pub output_contract: String,
    pub impact: String,
    pub authority: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ApplicationCapability {
    pub capability_id: String,
    pub meaning: String,
    pub application_posture: String,
    pub application_operation_ids: Vec<String>,
    pub application_deferred_reason: Option<String>,
    pub studio_posture: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ParticipantLinkInput {
    pub case_ref: String,
    pub participant_ref: String,
    pub principal_ref: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct StateMutationReceipt {
    pub changed: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub transition_ref: Option<String>,
    pub state: CaseVersionProjection,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct RegisteredModelsInput {
    pub tenant_id: String,
    pub target_ref: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ModelInventory {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub target_ref: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub observed_at_unix_ms: Option<u64>,
    pub models: Vec<String>,
    pub scope: String,
    pub authority: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ConversationTextPart {
    pub modality: TextModality,
    pub media_type: String,
    pub bytes: Vec<u8>,
}
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub enum TextModality {
    #[default]
    #[serde(rename = "text")]
    Text,
}
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub enum ContextDepth {
    #[default]
    #[serde(rename = "focused")]
    Focused,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ConversationIntent {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub context_depth: Option<ContextDepth>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub executor_participant_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub work_limits: Option<CaseWorkLimits>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub workflow_execution_id: Option<String>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct CaseWorkLimits {
    pub invocations: u16,
    pub operations: u16,
    pub effects: u16,
    pub max_input_units: usize,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_output_tokens: Option<u32>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct TextConversationInput {
    pub case_ref: String,
    pub participant_ref: String,
    pub thread_ref: String,
    pub submission_ref: String,
    pub expected_generation: u64,
    pub parts: Vec<ConversationTextPart>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub intent: Option<ConversationIntent>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ConversationResultSelection {
    pub selected_target_id: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ConversationPrimaryResult {
    pub result_id: String,
    pub invocation_id: String,
    pub output: String,
    pub selection: ConversationResultSelection,
}
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub enum ConversationPosture {
    #[default]
    #[serde(rename = "admitted")]
    Admitted,
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "provider_result_recorded")]
    ProviderResultRecorded,
    #[serde(rename = "refused")]
    Refused,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "cancelled")]
    Cancelled,
    #[serde(rename = "delivery_indeterminate")]
    DeliveryIndeterminate,
    #[serde(rename = "awaiting_review")]
    AwaitingReview,
    #[serde(rename = "budget_exhausted")]
    BudgetExhausted,
    #[serde(rename = "unresolved")]
    Unresolved,
}
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub enum CaseWorkPosture {
    #[default]
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "awaiting_review")]
    AwaitingReview,
    #[serde(rename = "delivery_indeterminate")]
    DeliveryIndeterminate,
    #[serde(rename = "budget_exhausted")]
    BudgetExhausted,
    #[serde(rename = "unresolved")]
    Unresolved,
    #[serde(rename = "cancelled_before_dispatch")]
    CancelledBeforeDispatch,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct CaseWorkStepObservation {
    pub ordinal: u16,
    pub source_ref: String,
    pub selection_ref: String,
    pub target_ref: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub invocation_ref: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub provider_result_ref: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub operation_ref: Option<String>,
    pub outcome_refs: Vec<String>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct CaseWorkObservation {
    pub schema: String,
    pub request_ref: String,
    pub participant_ref: String,
    pub thread_ref: String,
    pub observed_generation: u64,
    pub posture: CaseWorkPosture,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub answer: Option<String>,
    pub steps: Vec<CaseWorkStepObservation>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct AttemptObservation {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub outcome_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub target_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub attempt_number: Option<u64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub delivery: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stage: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub request_bytes_written: Option<u64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub response_status: Option<u64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub no_execution_proven: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub failure_class: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub recorded_at_unix_ms: Option<u64>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ConversationObservation {
    pub case_ref: String,
    pub participant_ref: String,
    pub submission_ref: String,
    pub turn_ref: String,
    pub request_ref: String,
    pub observed_generation: u64,
    pub posture: ConversationPosture,
    pub invocation_refs: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub primary_result: Option<ConversationPrimaryResult>,
    pub attempt_outcomes: Vec<AttemptObservation>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub work: Option<CaseWorkObservation>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct TextConversationSubmission {
    pub created: bool,
    pub execution: ConversationObservation,
}
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub enum ConversationDomain {
    #[default]
    #[serde(rename = "conversation")]
    Conversation,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ConversationExecutionReference {
    pub domain: ConversationDomain,
    pub submission_ref: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ConversationGetInput {
    pub case_ref: String,
    pub participant_ref: String,
    pub execution: ConversationExecutionReference,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ConversationWorkResumeInput {
    pub case_ref: String,
    pub participant_ref: String,
    pub submission_ref: String,
    pub observed_generation: u64,
}
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub enum ResultState {
    #[default]
    #[serde(rename = "success")]
    Success,
    #[serde(rename = "partial")]
    Partial,
    #[serde(rename = "unauthorized")]
    Unauthorized,
    #[serde(rename = "stale")]
    Stale,
    #[serde(rename = "core_pending")]
    CorePending,
    #[serde(rename = "not_implemented")]
    NotImplemented,
    #[serde(rename = "transport_unavailable")]
    TransportUnavailable,
    #[serde(rename = "error")]
    Error,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct OperationError {
    pub code: String,
    pub message: String,
    pub safe_message: String,
    pub result_state: ResultState,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct OperationResult {
    pub operation_ref: String,
    pub result_state: ResultState,
    pub correlation_ref: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<OperationError>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct CaseUpdate {
    pub protocol: String,
    pub event_ref: String,
    pub event_type: String,
    pub event_family: String,
    pub case_ref: String,
    pub generation: u64,
    pub sequence: u64,
    pub cursor: String,
    pub affected_views: Vec<String>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct GenerationCut {
    pub kind: GenerationCutKind,
    pub value: u64,
}
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub enum GenerationCutKind {
    #[default]
    #[serde(rename = "generation")]
    Generation,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct RecallBounds {
    pub candidates: usize,
    pub events: usize,
    pub relations: usize,
    pub segments: usize,
    pub expansion_depth: usize,
    pub semantic_units: usize,
    pub bytes: usize,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct RecallQuery {
    pub schema: String,
    pub case_id: String,
    pub expected_generation: u64,
    pub participant_id: String,
    pub at: GenerationCut,
    pub query: String,
    pub required_refs: Vec<String>,
    pub bounds: RecallBounds,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct RecallInput {
    pub request: RecallQuery,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct RecallCandidate {
    pub source_ref: String,
    pub plane: String,
    pub score_micros: i64,
    pub matched_terms: Vec<String>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct RecallTraceSummary {
    pub schema: String,
    pub trace_id: String,
    pub request_id: String,
    pub request: RecallQuery,
    pub generation: u64,
    pub disclosure_digest: String,
    pub qualified_source_digest: String,
    pub closure_complete: bool,
    pub omitted_candidates: usize,
    pub expansion_stopped_at_depth: bool,
    pub limitations: Vec<String>,
    pub candidates: Vec<RecallCandidate>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct RecallSelection {
    pub trace: RecallTraceSummary,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct WorkflowInput {
    pub case_ref: String,
    pub node_ref: String,
    pub value: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct WorkflowAdoptPatchInput {
    pub case_ref: String,
    pub patch_ref: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct HandoffAcceptInput {
    pub target_case_ref: String,
    pub source_case_ref: String,
    pub handoff_ref: String,
    pub participant_ref: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct HandoffReconcileInput {
    pub source_case_ref: String,
    pub handoff_ref: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ProcessAttachmentInput {
    pub case_ref: String,
    pub attachment_ref: String,
    pub pid: u32,
    pub policy_owner_participant_ref: String,
    pub actions: Vec<ProcessAction>,
    pub review_requirement: ReviewRequirement,
}
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub enum ProcessAction {
    #[default]
    #[serde(rename = "terminate")]
    Terminate,
    #[serde(rename = "suspend")]
    Suspend,
    #[serde(rename = "resume")]
    Resume,
}
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub enum ReviewRequirement {
    #[default]
    #[serde(rename = "automatic")]
    Automatic,
    #[serde(rename = "require_review")]
    RequireReview,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProductGrant {
    pub valid_from_unix_ms: Option<u64>,
    pub valid_until_unix_ms: Option<u64>,
    pub max_major_version: Option<u64>,
    pub updates_until_unix_ms: Option<u64>,
    pub offline_until_unix_ms: Option<u64>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EntitlementClaim {
    pub schema: String,
    pub product: String,
    pub edition: String,
    pub holder_ref: String,
    pub issuer_ref: String,
    pub evidence_ref: String,
    pub installation_ref: Option<String>,
    pub grants: Vec<ProductGrant>,
}
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub enum EntitlementPosture {
    #[default]
    #[serde(rename = "missing")]
    Missing,
    #[serde(rename = "unverifiable")]
    Unverifiable,
    #[serde(rename = "invalid")]
    Invalid,
    #[serde(rename = "expired")]
    Expired,
    #[serde(rename = "not_yet_valid")]
    NotYetValid,
    #[serde(rename = "version_not_covered")]
    VersionNotCovered,
    #[serde(rename = "stale")]
    Stale,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct EntitlementObservation {
    pub posture: EntitlementPosture,
    pub verification: String,
    pub access_granted: bool,
    pub observed_at_unix_ms: Option<u64>,
    pub claim: Option<EntitlementClaim>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ProductProfile {
    pub schema: String,
    pub profile_ref: String,
    pub installation_ref: String,
    pub principal_ref: String,
    pub selected_tenant_ref: Option<String>,
    pub entitlement_claim: Option<EntitlementClaim>,
    pub entitlement_observed_at_unix_ms: Option<u64>,
    pub created_at_unix_ms: u64,
    pub revision: u64,
}
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub enum BootstrapPosture {
    #[default]
    #[serde(rename = "identity_required")]
    IdentityRequired,
    #[serde(rename = "profile_required")]
    ProfileRequired,
    #[serde(rename = "workspace_required")]
    WorkspaceRequired,
    #[serde(rename = "workspace_selection_required")]
    WorkspaceSelectionRequired,
    #[serde(rename = "workspace_unavailable")]
    WorkspaceUnavailable,
    #[serde(rename = "ready")]
    Ready,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ProductAccess {
    pub product: String,
    pub version: String,
    pub access_policy: String,
    pub license_verification: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ProductAccount {
    pub posture: String,
    pub linkage: Option<String>,
    pub reason: String,
    pub sign_in_supported: bool,
    pub sign_out_supported: bool,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ProductPrincipal {
    pub posture: String,
    pub principal_ref: Option<String>,
    pub authentication_method: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ProductWorkspace {
    pub tenant_ref: String,
    pub display_name: String,
    pub kind: String,
    pub organization_ref: String,
    pub membership: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProductInitializeInput {
    pub create_personal_workspace: bool,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProductWorkspaceSelectInput {
    pub tenant_ref: String,
    pub expected_revision: u64,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProductEntitlementRecordInput {
    pub claim: Option<EntitlementClaim>,
    pub expected_revision: u64,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProductActivationStartInput {
    pub name: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProductActivationPollInput {
    pub activation_ref: String,
}
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub enum CommercialSessionPosture {
    #[default]
    #[serde(rename = "signed_out")]
    SignedOut,
    #[serde(rename = "activation_pending")]
    ActivationPending,
    #[serde(rename = "authenticated")]
    Authenticated,
    #[serde(rename = "credential_unavailable")]
    CredentialUnavailable,
}
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub enum ActivationPosture {
    #[default]
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "slow_down")]
    SlowDown,
    #[serde(rename = "activated")]
    Activated,
    #[serde(rename = "expired")]
    Expired,
    #[serde(rename = "denied")]
    Denied,
    #[serde(rename = "indeterminate")]
    Indeterminate,
}
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub enum CommercialServicePosture {
    #[default]
    #[serde(rename = "not_observed")]
    NotObserved,
    #[serde(rename = "reachable")]
    Reachable,
    #[serde(rename = "unavailable")]
    Unavailable,
    #[serde(rename = "credential_rejected")]
    CredentialRejected,
    #[serde(rename = "entitlement_refused")]
    EntitlementRefused,
    #[serde(rename = "unsupported_contract")]
    UnsupportedContract,
}
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub enum ProductAccessPosture {
    #[default]
    #[serde(rename = "trial_active")]
    TrialActive,
    #[serde(rename = "paid_active")]
    PaidActive,
    #[serde(rename = "not_yet_valid")]
    NotYetValid,
    #[serde(rename = "expired")]
    Expired,
    #[serde(rename = "revoked")]
    Revoked,
    #[serde(rename = "clock_rollback")]
    ClockRollback,
}
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub enum AcquiredAccessKind {
    #[default]
    #[serde(rename = "trial")]
    Trial,
    #[serde(rename = "subscription")]
    Subscription,
    #[serde(rename = "team")]
    Team,
}
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub enum EntitlementVerificationRefusal {
    #[default]
    #[serde(rename = "malformed")]
    Malformed,
    #[serde(rename = "unsupported_contract")]
    UnsupportedContract,
    #[serde(rename = "unsupported_issuer")]
    UnsupportedIssuer,
    #[serde(rename = "unsupported_key")]
    UnsupportedKey,
    #[serde(rename = "invalid_signature")]
    InvalidSignature,
    #[serde(rename = "invalid_installation_binding")]
    InvalidInstallationBinding,
    #[serde(rename = "invalid_claims")]
    InvalidClaims,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProductActivationObservation {
    pub activation_ref: String,
    pub posture: ActivationPosture,
    pub user_code: String,
    pub verification_uri: String,
    pub verification_uri_complete: String,
    pub expires_at_unix_ms: u64,
    pub poll_interval_ms: u64,
    pub next_poll_at_unix_ms: u64,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct VerifiedProductAccessObservation {
    pub schema: String,
    pub posture: ProductAccessPosture,
    pub licensed_operation_allowed: bool,
    pub account_ref: String,
    pub commercial_installation_ref: String,
    pub grant_ref: String,
    pub attestation_ref: String,
    pub attestation_digest: String,
    pub issuer_ref: String,
    pub key_ref: String,
    pub kind: AcquiredAccessKind,
    pub issued_at_unix_ms: u64,
    pub not_before_unix_ms: u64,
    pub valid_until_unix_ms: u64,
    pub offline_until_unix_ms: u64,
    pub observed_at_unix_ms: u64,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProductAuthObservation {
    pub schema: String,
    pub session: CommercialSessionPosture,
    pub service: CommercialServicePosture,
    pub account_ref: Option<String>,
    pub commercial_installation_ref: Option<String>,
    pub activation: Option<ProductActivationObservation>,
    pub access: Option<VerifiedProductAccessObservation>,
    pub verification_refusal: Option<EntitlementVerificationRefusal>,
    pub online_access_refused: bool,
    pub licensed_progress_allowed: bool,
    pub credential_storage: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ProductBootstrapProjection {
    pub schema: String,
    pub posture: BootstrapPosture,
    pub product: ProductAccess,
    pub account: ProductAccount,
    pub commercial_auth: Option<ProductAuthObservation>,
    pub profile: Option<ProductProfile>,
    pub local_home: String,
    pub principal: ProductPrincipal,
    pub entitlement: EntitlementObservation,
    pub workspaces: Vec<ProductWorkspace>,
    pub selected_workspace_ref: Option<String>,
    pub selected_workspace_available: bool,
    pub external_prerequisites: Vec<String>,
    pub case_authority: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CaseListInput {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<String>,
}
use crate::{ClientTransport, client::{Client, Error, Operation, Response}};
pub struct Identity<'a, T>(pub(crate) &'a Client<T>);
impl<T: ClientTransport> Client<T> {
    pub fn identity(&self) -> Identity<'_, T> { Identity(self) }
}
#[derive(Serialize)]
#[serde(transparent)]
struct IdentityCurrent<'a>(&'a EmptyInput);
impl Operation for IdentityCurrent<'_> {
    type Output = IdentityPresentation;
    const ID: &'static str = "identity.current";
    const INPUT_CONTRACT: Option<&'static str> = Some("yai.identity_current_input.v1");
    const OUTPUT_CONTRACT: Option<&'static str> = Some("yai.identity_projection.v1");
}
impl<T: ClientTransport> Identity<'_, T> {
    pub fn current(&self, correlation: &str, input: &EmptyInput) -> Result<Response<IdentityPresentation>, Error> {
        self.0.execute(correlation, &IdentityCurrent(input))
    }
}
pub struct Knowledge<'a, T>(pub(crate) &'a Client<T>);
impl<T: ClientTransport> Client<T> {
    pub fn knowledge(&self) -> Knowledge<'_, T> { Knowledge(self) }
}
#[derive(Serialize)]
#[serde(transparent)]
struct KnowledgeInspect<'a>(&'a KnowledgeInspectInput);
impl Operation for KnowledgeInspect<'_> {
    type Output = KnowledgeView;
    const ID: &'static str = "knowledge.inspect";
    const INPUT_CONTRACT: Option<&'static str> = Some("yai.knowledge_inspect_input.v1");
    const OUTPUT_CONTRACT: Option<&'static str> = Some("yai.source_knowledge.v1");
}
impl<T: ClientTransport> Knowledge<'_, T> {
    pub fn inspect(&self, correlation: &str, input: &KnowledgeInspectInput) -> Result<Response<KnowledgeView>, Error> {
        self.0.execute(correlation, &KnowledgeInspect(input))
    }
}
#[derive(Serialize)]
#[serde(transparent)]
struct KnowledgeSearch<'a>(&'a KnowledgeSearchInput);
impl Operation for KnowledgeSearch<'_> {
    type Output = KnowledgeSearchResult;
    const ID: &'static str = "knowledge.search";
    const INPUT_CONTRACT: Option<&'static str> = Some("yai.knowledge_search_input.v1");
    const OUTPUT_CONTRACT: Option<&'static str> = Some("yai.knowledge_search_result.v1");
}
impl<T: ClientTransport> Knowledge<'_, T> {
    pub fn search(&self, correlation: &str, input: &KnowledgeSearchInput) -> Result<Response<KnowledgeSearchResult>, Error> {
        self.0.execute(correlation, &KnowledgeSearch(input))
    }
}
#[derive(Serialize)]
#[serde(transparent)]
struct KnowledgeResolve<'a>(&'a KnowledgeResolveInput);
impl Operation for KnowledgeResolve<'_> {
    type Output = KnowledgeResolveResult;
    const ID: &'static str = "knowledge.resolve";
    const INPUT_CONTRACT: Option<&'static str> = Some("yai.knowledge_resolve_input.v1");
    const OUTPUT_CONTRACT: Option<&'static str> = Some("yai.knowledge_resolve_result.v1");
}
impl<T: ClientTransport> Knowledge<'_, T> {
    pub fn resolve(&self, correlation: &str, input: &KnowledgeResolveInput) -> Result<Response<KnowledgeResolveResult>, Error> {
        self.0.execute(correlation, &KnowledgeResolve(input))
    }
}
#[derive(Serialize)]
#[serde(transparent)]
struct KnowledgeNavigation<'a>(&'a KnowledgeInspectInput);
impl Operation for KnowledgeNavigation<'_> {
    type Output = KnowledgeNavigationResult;
    const ID: &'static str = "knowledge.navigation";
    const INPUT_CONTRACT: Option<&'static str> = Some("yai.knowledge_inspect_input.v1");
    const OUTPUT_CONTRACT: Option<&'static str> = Some("yai.knowledge_navigation_result.v1");
}
impl<T: ClientTransport> Knowledge<'_, T> {
    pub fn navigation(&self, correlation: &str, input: &KnowledgeInspectInput) -> Result<Response<KnowledgeNavigationResult>, Error> {
        self.0.execute(correlation, &KnowledgeNavigation(input))
    }
}
pub struct Cases<'a, T>(pub(crate) &'a Client<T>);
impl<T: ClientTransport> Client<T> {
    pub fn cases(&self) -> Cases<'_, T> { Cases(self) }
}
#[derive(Serialize)]
#[serde(transparent)]
struct CasesList<'a>(&'a CaseListInput);
impl Operation for CasesList<'_> {
    type Output = CaseListProjection;
    const ID: &'static str = "case.list";
    const INPUT_CONTRACT: Option<&'static str> = Some("yai.case_list_input.v1");
    const OUTPUT_CONTRACT: Option<&'static str> = Some("yai.case_list_projection.v1");
}
impl<T: ClientTransport> Cases<'_, T> {
    pub fn list(&self, correlation: &str, input: &CaseListInput) -> Result<Response<CaseListProjection>, Error> {
        self.0.execute(correlation, &CasesList(input))
    }
}
#[derive(Serialize)]
#[serde(transparent)]
struct CasesRecent<'a>(&'a CaseListInput);
impl Operation for CasesRecent<'_> {
    type Output = CaseListProjection;
    const ID: &'static str = "case.recent";
    const INPUT_CONTRACT: Option<&'static str> = Some("yai.case_list_input.v1");
    const OUTPUT_CONTRACT: Option<&'static str> = Some("yai.case_list_projection.v1");
}
impl<T: ClientTransport> Cases<'_, T> {
    pub fn recent(&self, correlation: &str, input: &CaseListInput) -> Result<Response<CaseListProjection>, Error> {
        self.0.execute(correlation, &CasesRecent(input))
    }
}
#[derive(Serialize)]
#[serde(transparent)]
struct CasesOpen<'a>(&'a CaseRefInput);
impl Operation for CasesOpen<'_> {
    type Output = CaseAttachment;
    const ID: &'static str = "case.open";
    const INPUT_CONTRACT: Option<&'static str> = Some("yai.case_open_input.v1");
    const OUTPUT_CONTRACT: Option<&'static str> = Some("yai.case_attachment.v1");
}
impl<T: ClientTransport> Cases<'_, T> {
    pub fn open(&self, correlation: &str, input: &CaseRefInput) -> Result<Response<CaseAttachment>, Error> {
        self.0.execute(correlation, &CasesOpen(input))
    }
}
#[derive(Serialize)]
#[serde(transparent)]
struct CasesCreate<'a>(&'a CaseCreateInput);
impl Operation for CasesCreate<'_> {
    type Output = WorkCommit;
    const ID: &'static str = "case.create";
    const INPUT_CONTRACT: Option<&'static str> = Some("yai.case_create_input.v1");
    const OUTPUT_CONTRACT: Option<&'static str> = Some("yai.canonical_commit.v1");
}
impl<T: ClientTransport> Cases<'_, T> {
    pub fn create(&self, correlation: &str, input: &CaseCreateInput) -> Result<Response<WorkCommit>, Error> {
        self.0.execute(correlation, &CasesCreate(input))
    }
}
pub struct Authority<'a, T>(pub(crate) &'a Client<T>);
impl<T: ClientTransport> Client<T> {
    pub fn authority(&self) -> Authority<'_, T> { Authority(self) }
}
#[derive(Serialize)]
#[serde(transparent)]
struct AuthorityAddRole<'a>(&'a ParticipantRoleInput);
impl Operation for AuthorityAddRole<'_> {
    type Output = StateMutationReceipt;
    const ID: &'static str = "participant.role.add";
    const INPUT_CONTRACT: Option<&'static str> = Some("yai.participant_role_add_input.v1");
    const OUTPUT_CONTRACT: Option<&'static str> = Some("yai.case_state_mutation_result.v1");
}
impl<T: ClientTransport> Authority<'_, T> {
    pub fn add_role(&self, correlation: &str, input: &ParticipantRoleInput) -> Result<Response<StateMutationReceipt>, Error> {
        self.0.execute(correlation, &AuthorityAddRole(input))
    }
}
#[derive(Serialize)]
#[serde(transparent)]
struct AuthorityApprove<'a>(&'a ReviewResolveInput);
impl Operation for AuthorityApprove<'_> {
    type Output = ReviewResolveResult;
    const ID: &'static str = "review.approve";
    const INPUT_CONTRACT: Option<&'static str> = Some("yai.review_resolve_input.v1");
    const OUTPUT_CONTRACT: Option<&'static str> = Some("yai.review_resolve_result.v1");
}
impl<T: ClientTransport> Authority<'_, T> {
    pub fn approve(&self, correlation: &str, input: &ReviewResolveInput) -> Result<Response<ReviewResolveResult>, Error> {
        self.0.execute(correlation, &AuthorityApprove(input))
    }
}
#[derive(Serialize)]
#[serde(transparent)]
struct AuthorityDeny<'a>(&'a ReviewResolveInput);
impl Operation for AuthorityDeny<'_> {
    type Output = ReviewResolveResult;
    const ID: &'static str = "review.deny";
    const INPUT_CONTRACT: Option<&'static str> = Some("yai.review_resolve_input.v1");
    const OUTPUT_CONTRACT: Option<&'static str> = Some("yai.review_resolve_result.v1");
}
impl<T: ClientTransport> Authority<'_, T> {
    pub fn deny(&self, correlation: &str, input: &ReviewResolveInput) -> Result<Response<ReviewResolveResult>, Error> {
        self.0.execute(correlation, &AuthorityDeny(input))
    }
}
#[derive(Serialize)]
#[serde(transparent)]
struct AuthorityDefer<'a>(&'a ReviewResolveInput);
impl Operation for AuthorityDefer<'_> {
    type Output = ReviewResolveResult;
    const ID: &'static str = "review.defer";
    const INPUT_CONTRACT: Option<&'static str> = Some("yai.review_resolve_input.v1");
    const OUTPUT_CONTRACT: Option<&'static str> = Some("yai.review_resolve_result.v1");
}
impl<T: ClientTransport> Authority<'_, T> {
    pub fn defer(&self, correlation: &str, input: &ReviewResolveInput) -> Result<Response<ReviewResolveResult>, Error> {
        self.0.execute(correlation, &AuthorityDefer(input))
    }
}
#[derive(Serialize)]
#[serde(transparent)]
struct AuthorityLinkPrincipal<'a>(&'a ParticipantLinkInput);
impl Operation for AuthorityLinkPrincipal<'_> {
    type Output = StateMutationReceipt;
    const ID: &'static str = "participant.principal.link";
    const INPUT_CONTRACT: Option<&'static str> = Some("yai.participant_principal_link_input.v1");
    const OUTPUT_CONTRACT: Option<&'static str> = Some("yai.case_state_mutation_result.v1");
}
impl<T: ClientTransport> Authority<'_, T> {
    pub fn link_principal(&self, correlation: &str, input: &ParticipantLinkInput) -> Result<Response<StateMutationReceipt>, Error> {
        self.0.execute(correlation, &AuthorityLinkPrincipal(input))
    }
}
pub struct Materials<'a, T>(pub(crate) &'a Client<T>);
impl<T: ClientTransport> Client<T> {
    pub fn materials(&self) -> Materials<'_, T> { Materials(self) }
}
#[derive(Serialize)]
#[serde(transparent)]
struct MaterialsRead<'a>(&'a MaterialReadInput);
impl Operation for MaterialsRead<'_> {
    type Output = MaterialReadResult;
    const ID: &'static str = "material.read";
    const INPUT_CONTRACT: Option<&'static str> = Some("yai.material_read_input.v1");
    const OUTPUT_CONTRACT: Option<&'static str> = Some("yai.material_read_projection.v1");
}
impl<T: ClientTransport> Materials<'_, T> {
    pub fn read(&self, correlation: &str, input: &MaterialReadInput) -> Result<Response<MaterialReadResult>, Error> {
        self.0.execute(correlation, &MaterialsRead(input))
    }
}
pub struct Compute<'a, T>(pub(crate) &'a Client<T>);
impl<T: ClientTransport> Client<T> {
    pub fn compute(&self) -> Compute<'_, T> { Compute(self) }
}
#[derive(Serialize)]
#[serde(transparent)]
struct ComputeModels<'a>(&'a RegisteredModelsInput);
impl Operation for ComputeModels<'_> {
    type Output = ModelInventory;
    const ID: &'static str = "provider.models";
    const INPUT_CONTRACT: Option<&'static str> = Some("yai.provider_models_input.v1");
    const OUTPUT_CONTRACT: Option<&'static str> = Some("yai.provider_models.v1");
}
impl<T: ClientTransport> Compute<'_, T> {
    pub fn models(&self, correlation: &str, input: &RegisteredModelsInput) -> Result<Response<ModelInventory>, Error> {
        self.0.execute(correlation, &ComputeModels(input))
    }
}
pub struct Conversation<'a, T>(pub(crate) &'a Client<T>);
impl<T: ClientTransport> Client<T> {
    pub fn conversation(&self) -> Conversation<'_, T> { Conversation(self) }
}
#[derive(Serialize)]
#[serde(transparent)]
struct ConversationSendText<'a>(&'a TextConversationInput);
impl Operation for ConversationSendText<'_> {
    type Output = TextConversationSubmission;
    const ID: &'static str = "conversation.send";
    const INPUT_CONTRACT: Option<&'static str> = Some("yai.conversation_send_input.v1");
    const OUTPUT_CONTRACT: Option<&'static str> = Some("yai.conversation_submission_result.v1");
}
impl<T: ClientTransport> Conversation<'_, T> {
    pub fn send_text(&self, correlation: &str, input: &TextConversationInput) -> Result<Response<TextConversationSubmission>, Error> {
        self.0.execute(correlation, &ConversationSendText(input))
    }
}
#[derive(Serialize)]
#[serde(transparent)]
struct ConversationResumeWork<'a>(&'a ConversationWorkResumeInput);
impl Operation for ConversationResumeWork<'_> {
    type Output = TextConversationSubmission;
    const ID: &'static str = "conversation.work.resume";
    const INPUT_CONTRACT: Option<&'static str> = Some("yai.conversation_work_resume_input.v1");
    const OUTPUT_CONTRACT: Option<&'static str> = Some("yai.conversation_submission_result.v1");
}
impl<T: ClientTransport> Conversation<'_, T> {
    pub fn resume_work(&self, correlation: &str, input: &ConversationWorkResumeInput) -> Result<Response<TextConversationSubmission>, Error> {
        self.0.execute(correlation, &ConversationResumeWork(input))
    }
}
#[derive(Serialize)]
#[serde(transparent)]
struct ConversationGet<'a>(&'a ConversationGetInput);
impl Operation for ConversationGet<'_> {
    type Output = ConversationObservation;
    const ID: &'static str = "execution.get";
    const INPUT_CONTRACT: Option<&'static str> = Some("yai.execution_get_input.v1");
    const OUTPUT_CONTRACT: Option<&'static str> = Some("yai.execution_observation.v1");
}
impl<T: ClientTransport> Conversation<'_, T> {
    pub fn get(&self, correlation: &str, input: &ConversationGetInput) -> Result<Response<ConversationObservation>, Error> {
        self.0.execute(correlation, &ConversationGet(input))
    }
}
pub struct Memory<'a, T>(pub(crate) &'a Client<T>);
impl<T: ClientTransport> Client<T> {
    pub fn memory(&self) -> Memory<'_, T> { Memory(self) }
}
#[derive(Serialize)]
#[serde(transparent)]
struct MemoryRecall<'a>(&'a RecallInput);
impl Operation for MemoryRecall<'_> {
    type Output = RecallSelection;
    const ID: &'static str = "semantic.recall";
    const INPUT_CONTRACT: Option<&'static str> = Some("yai.recall_execute_input.v1");
    const OUTPUT_CONTRACT: Option<&'static str> = Some("yai.recall_result.v2");
}
impl<T: ClientTransport> Memory<'_, T> {
    pub fn recall(&self, correlation: &str, input: &RecallInput) -> Result<Response<RecallSelection>, Error> {
        self.0.execute(correlation, &MemoryRecall(input))
    }
}
pub struct Work<'a, T>(pub(crate) &'a Client<T>);
impl<T: ClientTransport> Client<T> {
    pub fn work(&self) -> Work<'_, T> { Work(self) }
}
#[derive(Serialize)]
#[serde(transparent)]
struct WorkRecordInput<'a>(&'a WorkflowInput);
impl Operation for WorkRecordInput<'_> {
    type Output = WorkCommit;
    const ID: &'static str = "workflow.input.record";
    const INPUT_CONTRACT: Option<&'static str> = Some("yai.workflow_input_record_input.v1");
    const OUTPUT_CONTRACT: Option<&'static str> = Some("yai.canonical_commit.v1");
}
impl<T: ClientTransport> Work<'_, T> {
    pub fn record_input(&self, correlation: &str, input: &WorkflowInput) -> Result<Response<WorkCommit>, Error> {
        self.0.execute(correlation, &WorkRecordInput(input))
    }
}
#[derive(Serialize)]
#[serde(transparent)]
struct WorkAdoptPatch<'a>(&'a WorkflowAdoptPatchInput);
impl Operation for WorkAdoptPatch<'_> {
    type Output = WorkCommit;
    const ID: &'static str = "workflow.patch.adopt";
    const INPUT_CONTRACT: Option<&'static str> = Some("yai.workflow_patch_adopt_input.v1");
    const OUTPUT_CONTRACT: Option<&'static str> = Some("yai.canonical_commit.v1");
}
impl<T: ClientTransport> Work<'_, T> {
    pub fn adopt_patch(&self, correlation: &str, input: &WorkflowAdoptPatchInput) -> Result<Response<WorkCommit>, Error> {
        self.0.execute(correlation, &WorkAdoptPatch(input))
    }
}
pub struct Handoff<'a, T>(pub(crate) &'a Client<T>);
impl<T: ClientTransport> Client<T> {
    pub fn handoff(&self) -> Handoff<'_, T> { Handoff(self) }
}
#[derive(Serialize)]
#[serde(transparent)]
struct HandoffAccept<'a>(&'a HandoffAcceptInput);
impl Operation for HandoffAccept<'_> {
    type Output = WorkCommit;
    const ID: &'static str = "handoff.accept";
    const INPUT_CONTRACT: Option<&'static str> = Some("yai.handoff_accept_input.v1");
    const OUTPUT_CONTRACT: Option<&'static str> = Some("yai.canonical_commit.v1");
}
impl<T: ClientTransport> Handoff<'_, T> {
    pub fn accept(&self, correlation: &str, input: &HandoffAcceptInput) -> Result<Response<WorkCommit>, Error> {
        self.0.execute(correlation, &HandoffAccept(input))
    }
}
#[derive(Serialize)]
#[serde(transparent)]
struct HandoffReconcile<'a>(&'a HandoffReconcileInput);
impl Operation for HandoffReconcile<'_> {
    type Output = WorkCommit;
    const ID: &'static str = "handoff.reconcile";
    const INPUT_CONTRACT: Option<&'static str> = Some("yai.handoff_reconcile_input.v1");
    const OUTPUT_CONTRACT: Option<&'static str> = Some("yai.canonical_commit.v1");
}
impl<T: ClientTransport> Handoff<'_, T> {
    pub fn reconcile(&self, correlation: &str, input: &HandoffReconcileInput) -> Result<Response<WorkCommit>, Error> {
        self.0.execute(correlation, &HandoffReconcile(input))
    }
}
pub struct Resources<'a, T>(pub(crate) &'a Client<T>);
impl<T: ClientTransport> Client<T> {
    pub fn resources(&self) -> Resources<'_, T> { Resources(self) }
}
#[derive(Serialize)]
#[serde(transparent)]
struct ResourcesAttachProcess<'a>(&'a ProcessAttachmentInput);
impl Operation for ResourcesAttachProcess<'_> {
    type Output = StateMutationReceipt;
    const ID: &'static str = "resource.attach_process";
    const INPUT_CONTRACT: Option<&'static str> = Some("yai.resource_attach_process_input.v1");
    const OUTPUT_CONTRACT: Option<&'static str> = Some("yai.case_state_mutation_result.v1");
}
impl<T: ClientTransport> Resources<'_, T> {
    pub fn attach_process(&self, correlation: &str, input: &ProcessAttachmentInput) -> Result<Response<StateMutationReceipt>, Error> {
        self.0.execute(correlation, &ResourcesAttachProcess(input))
    }
}
pub struct Product<'a, T>(pub(crate) &'a Client<T>);
impl<T: ClientTransport> Client<T> {
    pub fn product(&self) -> Product<'_, T> { Product(self) }
}
#[derive(Serialize)]
#[serde(transparent)]
struct ProductActivationStart<'a>(&'a ProductActivationStartInput);
impl Operation for ProductActivationStart<'_> {
    type Output = ProductAuthObservation;
    const ID: &'static str = "product.activation.start";
    const INPUT_CONTRACT: Option<&'static str> = Some("yai.product_activation_start_input.v1");
    const OUTPUT_CONTRACT: Option<&'static str> = Some("yai.product_auth.v1");
}
impl<T: ClientTransport> Product<'_, T> {
    pub fn activation_start(&self, correlation: &str, input: &ProductActivationStartInput) -> Result<Response<ProductAuthObservation>, Error> {
        self.0.execute(correlation, &ProductActivationStart(input))
    }
}
#[derive(Serialize)]
#[serde(transparent)]
struct ProductActivationPoll<'a>(&'a ProductActivationPollInput);
impl Operation for ProductActivationPoll<'_> {
    type Output = ProductAuthObservation;
    const ID: &'static str = "product.activation.poll";
    const INPUT_CONTRACT: Option<&'static str> = Some("yai.product_activation_poll_input.v1");
    const OUTPUT_CONTRACT: Option<&'static str> = Some("yai.product_auth.v1");
}
impl<T: ClientTransport> Product<'_, T> {
    pub fn activation_poll(&self, correlation: &str, input: &ProductActivationPollInput) -> Result<Response<ProductAuthObservation>, Error> {
        self.0.execute(correlation, &ProductActivationPoll(input))
    }
}
#[derive(Serialize)]
#[serde(transparent)]
struct ProductAuth<'a>(&'a EmptyInput);
impl Operation for ProductAuth<'_> {
    type Output = ProductAuthObservation;
    const ID: &'static str = "product.auth.get";
    const INPUT_CONTRACT: Option<&'static str> = Some("yai.product_auth_get_input.v1");
    const OUTPUT_CONTRACT: Option<&'static str> = Some("yai.product_auth.v1");
}
impl<T: ClientTransport> Product<'_, T> {
    pub fn auth(&self, correlation: &str, input: &EmptyInput) -> Result<Response<ProductAuthObservation>, Error> {
        self.0.execute(correlation, &ProductAuth(input))
    }
}
#[derive(Serialize)]
#[serde(transparent)]
struct ProductRefreshAuth<'a>(&'a EmptyInput);
impl Operation for ProductRefreshAuth<'_> {
    type Output = ProductAuthObservation;
    const ID: &'static str = "product.auth.refresh";
    const INPUT_CONTRACT: Option<&'static str> = Some("yai.product_auth_refresh_input.v1");
    const OUTPUT_CONTRACT: Option<&'static str> = Some("yai.product_auth.v1");
}
impl<T: ClientTransport> Product<'_, T> {
    pub fn refresh_auth(&self, correlation: &str, input: &EmptyInput) -> Result<Response<ProductAuthObservation>, Error> {
        self.0.execute(correlation, &ProductRefreshAuth(input))
    }
}
#[derive(Serialize)]
#[serde(transparent)]
struct ProductSignOut<'a>(&'a EmptyInput);
impl Operation for ProductSignOut<'_> {
    type Output = ProductAuthObservation;
    const ID: &'static str = "product.auth.sign_out";
    const INPUT_CONTRACT: Option<&'static str> = Some("yai.product_auth_sign_out_input.v1");
    const OUTPUT_CONTRACT: Option<&'static str> = Some("yai.product_auth.v1");
}
impl<T: ClientTransport> Product<'_, T> {
    pub fn sign_out(&self, correlation: &str, input: &EmptyInput) -> Result<Response<ProductAuthObservation>, Error> {
        self.0.execute(correlation, &ProductSignOut(input))
    }
}
#[derive(Serialize)]
#[serde(transparent)]
struct ProductBootstrap<'a>(&'a EmptyInput);
impl Operation for ProductBootstrap<'_> {
    type Output = ProductBootstrapProjection;
    const ID: &'static str = "product.bootstrap.get";
    const INPUT_CONTRACT: Option<&'static str> = Some("yai.product_bootstrap_get_input.v1");
    const OUTPUT_CONTRACT: Option<&'static str> = Some("yai.product_bootstrap.v1");
}
impl<T: ClientTransport> Product<'_, T> {
    pub fn bootstrap(&self, correlation: &str, input: &EmptyInput) -> Result<Response<ProductBootstrapProjection>, Error> {
        self.0.execute(correlation, &ProductBootstrap(input))
    }
}
#[derive(Serialize)]
#[serde(transparent)]
struct ProductInitialize<'a>(&'a ProductInitializeInput);
impl Operation for ProductInitialize<'_> {
    type Output = ProductBootstrapProjection;
    const ID: &'static str = "product.profile.initialize";
    const INPUT_CONTRACT: Option<&'static str> = Some("yai.product_profile_initialize_input.v1");
    const OUTPUT_CONTRACT: Option<&'static str> = Some("yai.product_bootstrap.v1");
}
impl<T: ClientTransport> Product<'_, T> {
    pub fn initialize(&self, correlation: &str, input: &ProductInitializeInput) -> Result<Response<ProductBootstrapProjection>, Error> {
        self.0.execute(correlation, &ProductInitialize(input))
    }
}
#[derive(Serialize)]
#[serde(transparent)]
struct ProductSelectWorkspace<'a>(&'a ProductWorkspaceSelectInput);
impl Operation for ProductSelectWorkspace<'_> {
    type Output = ProductBootstrapProjection;
    const ID: &'static str = "product.workspace.select";
    const INPUT_CONTRACT: Option<&'static str> = Some("yai.product_workspace_select_input.v1");
    const OUTPUT_CONTRACT: Option<&'static str> = Some("yai.product_bootstrap.v1");
}
impl<T: ClientTransport> Product<'_, T> {
    pub fn select_workspace(&self, correlation: &str, input: &ProductWorkspaceSelectInput) -> Result<Response<ProductBootstrapProjection>, Error> {
        self.0.execute(correlation, &ProductSelectWorkspace(input))
    }
}
#[derive(Serialize)]
#[serde(transparent)]
struct ProductRecordEntitlement<'a>(&'a ProductEntitlementRecordInput);
impl Operation for ProductRecordEntitlement<'_> {
    type Output = ProductBootstrapProjection;
    const ID: &'static str = "product.entitlement.record";
    const INPUT_CONTRACT: Option<&'static str> = Some("yai.product_entitlement_record_input.v1");
    const OUTPUT_CONTRACT: Option<&'static str> = Some("yai.product_bootstrap.v1");
}
impl<T: ClientTransport> Product<'_, T> {
    pub fn record_entitlement(&self, correlation: &str, input: &ProductEntitlementRecordInput) -> Result<Response<ProductBootstrapProjection>, Error> {
        self.0.execute(correlation, &ProductRecordEntitlement(input))
    }
}
