// Generated by tools/yvex_management.py; safe native connection records.
use serde::{Serialize, Deserialize};
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct IdentityObservation {
    pub schema: String,
    pub device_identity: String,
    pub display_name: String,
    pub protocol: String,
    pub pairing_available: bool,
}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct HostCandidate {
    pub endpoint: String,
    pub identity: IdentityObservation,
    pub certificate_sha256: String,
}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all="snake_case")]
pub enum PairingPosture {Pending,Approved,Revoked,Expired,Refused}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PairingObservation {
    pub schema: String,
    pub request_id: String,
    pub posture: PairingPosture,
    pub scope: String,
    pub expires_at_unix_ms: u64,
    pub reason: Option<String>,
}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all="snake_case")]
pub enum ConnectionTransport {Https,Local}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all="snake_case")]
pub enum ConnectionPosture {Unpaired,Pending,Approved,Revoked,Expired,Refused}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ConnectionProfile {
    pub profile_ref: String,
    pub transport: ConnectionTransport,
    pub endpoint: String,
    pub device_identity: String,
    pub peer_identity: String,
    pub display_name: String,
    pub client_name: String,
    pub pairing_posture: ConnectionPosture,
    pub expires_at_unix_ms: Option<u64>,
}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DiscoveredHost {
    pub service_name: String,
    pub endpoint: String,
    pub display_name: String,
    pub advertised_device_identity: Option<String>,
    pub trusted: bool,
}
